// Every visible Turkish string of the Revak Okulları concept lives here, so an
// English file can be added later with the same shape (`const en: RevakCopy`).
// Revak Okulları is a fictional brand; people, numbers and placements are
// illustrative (see footer.note).

import type { Kademe } from "@/lib/revak/store";
import type { ImageKey } from "./images";

const img = (k: ImageKey) => k;

export type SinifOption = { id: string; label: string; age: [number, number] };

export const tr = {
  meta: {
    title: "Revak Okulları | Anaokulundan liseye, Sarıyer",
    description:
      "Sarıyer Zekeriyaköy'de anaokulundan liseye tek kampüs. Sınıflar en fazla 18 öğrenci, IB Diploma Programı, üç dil. Kampüs turu planlayın, ön kayıt yaptırın.",
  },

  strip: { text: "Konsept çalışma — rasitburucu.com", href: "/tr" },
  skip: "İçeriğe geç",
  crumb: "Bulunduğunuz sayfa",

  announce: {
    lead: "Bursluluk sınavı",
    // {date} {weekday} {deadline} {days}
    text: (date: string, weekday: string, deadline: string, days: number) =>
      days > 0
        ? `${date} ${weekday}. Son başvuru ${deadline}; ${days} gün kaldı.`
        : `${date} ${weekday}. Başvurular bugün kapanıyor.`,
    cta: "Sınava başvurun",
    close: "Duyuruyu kapat",
  },

  brand: { name: "Revak", full: "Revak Okulları", home: "Revak Okulları ana sayfa" },

  nav: {
    label: "Ana menü",
    items: [
      { label: "Okulumuz", href: "/revak/#yaklasim" },
      { label: "Eğitim", href: "/revak/#kademeler" },
      { label: "Kampüs", href: "/revak/kampus/" },
      { label: "Yaşam", href: "/revak/kampus/#bir-gun" },
      { label: "Kabul", href: "/revak/kabul/" },
      { label: "İletişim", href: "#iletisim" },
    ],
    tour: "Kampüs turu",
    apply: "Ön kayıt",
    parents: "Veli girişi",
    menu: "Menü",
    close: "Menüyü kapat",
  },

  mobileBar: { label: "Hızlı erişim", tour: "Tur", apply: "Ön kayıt", call: "Ara" },

  contact: {
    phone: "0212 000 19 87",
    phoneHref: "tel:+902120001987",
    email: "kabul@revak.k12.tr",
    address: ["Çamlık Yolu No: 12, Zekeriyaköy", "34450 Sarıyer, İstanbul"],
    hours: "Kabul ofisi hafta içi 08.30-17.30",
    mapsHref: "https://www.google.com/maps/search/?api=1&query=Zekeriyak%C3%B6y+Sar%C4%B1yer+%C4%B0stanbul",
  },

  /* ---------------- home ---------------- */

  hero: {
    title: "Her çocuğun adıyla tanındığı okul.",
    // Hand-set line breaks for the display setting; the second line is set in italic.
    titleLines: ["Her çocuğun", "adıyla", "tanındığı okul."],
    masthead: ["Revak Okulları", "Anaokulundan liseye", "Zekeriyaköy, Sarıyer", "2027-2028 kabul dönemi"],
    caption: "Lev. 0 — Revak, sabah ışığında",
    sub: "Sınıflarımız 18 öğrenciyi geçmez; her öğrencinin kendi danışman öğretmeni vardır. Çocuğunuzun nasıl öğrendiğini, neye sevindiğini biz de biliriz.",
    primary: "Ön kayıt yaptırın",
    secondary: "Kampüs turu planlayın",
    imageAlt: "Taş kemerlerin altından geçen gölgeli bir revak",
  },

  sentence: {
    label: "Nereden başlamak istersiniz?",
    before: "Çocuğum",
    middle: "için",
    after: "istiyorum.",
    kademeLabel: "Kademe",
    intentLabel: "Ne yapmak istiyorsunuz?",
    kademe: { anaokulu: "anaokulu", ilkokul: "ilkokul", ortaokul: "ortaokul", lise: "lise" } as Record<Kademe, string>,
    intents: [
      { id: "on-kayit", label: "ön kayıt yaptırmak" },
      { id: "tur", label: "kampüsü görmek" },
      { id: "ucret", label: "ücret bilgisi almak" },
      { id: "burs", label: "bursluluk sınavına girmek" },
    ],
    go: "Devam edin",
  },

  proof: {
    title: "Kısaca Revak.",
    folio: "§ 01",
    // One typographic paragraph: each numeral sits in the running text.
    lines: [
      { pre: "Her sınıfta en fazla ", big: "18", post: " öğrenci." },
      { pre: "Anaokulunda başlayan ", big: "3", post: " dil." },
      { pre: "", big: "2014", post: "'ten beri IB Diploma Programı." },
      { pre: "Anaokulundan liseye ", big: "1", post: " kampüs." },
    ],
    notes: [
      "Anaokulunda 14 çocuk ve iki öğretmen.",
      "Türkçe ve İngilizce anaokulunda başlar; 5. sınıfta Almanca ya da İspanyolca eklenir.",
      "Lisenin son iki yılında, isteyen her öğrenciye açık.",
      "Aynı bahçe, aynı kapı. Kardeşler aynı servise biner.",
    ],
    items: [
      { big: "En fazla 18 öğrenci", text: "Her sınıfta. Anaokulunda 14 çocuk ve iki öğretmen." },
      { big: "Üç dil", text: "Türkçe ve İngilizce anaokulunda başlar; 5. sınıfta Almanca ya da İspanyolca eklenir." },
      { big: "IB Diploma Programı", text: "2014'ten beri, lisenin son iki yılında isteyen her öğrenciye açık." },
      { big: "Tek kampüs", text: "Anaokulundan liseye aynı bahçe. Kardeşler aynı servise biner, aynı kapıdan girer." },
    ],
  },

  levels: {
    folio: "§ 02",
    title: "Revak boyunca",
    plate: "Lev.",
    rulerLabel: "Kademeler",
    ageLabel: "yaş",
    exit: {
      title: "Revağın sonunda, dünya.",
      text: "2026'da 92 mezun. 71'i yurt içinde, 21'i yurt dışında bir üniversitede.",
      link: "Mezunlarımız nereye gitti",
    },
    intro:
      "Anaokulundan liseye dört kademe, tek bir çatı altında. Çocuğunuz büyüdükçe okul da onunla birlikte değişir; onu tanıyan yüzler değişmez.",
    cta: "Bu kademe için ön kayıt",
    classSize: "Sınıf mevcudu",
    languages: "Diller",
    items: {
      anaokulu: {
        name: "Anaokulu",
        range: "3-5 yaş",
        size: "14 çocuk, iki öğretmen",
        lang: "İngilizce her gün, oyunla",
        line: "Kendi bahçesi olan ayrı bir bina. Günün yarısı açık havada, yarısı atölyede geçer.",
        quote: "Sabah kapıda her çocuğu adıyla karşılarız. Günün geri kalanı o selamla başlar.",
        who: "Defne Yalçın, anaokulu öğretmeni",
        image: img("anaokulu"),
      },
      ilkokul: {
        name: "İlkokul",
        range: "1-4. sınıf",
        size: "En fazla 18 öğrenci",
        lang: "Haftada 10 saat İngilizce",
        line: "Okuma saatiyle başlayan günler, her dönem bir çalgı, haftada iki gün yüzme.",
        quote: "Okumayı sevdirmek için acele etmeyiz. Her çocuğun kendi hızında bir kitabı olur.",
        who: "Elif Sönmez, 2. sınıf öğretmeni",
        image: img("ilkokul"),
      },
      ortaokul: {
        name: "Ortaokul",
        range: "5-8. sınıf",
        size: "En fazla 18 öğrenci",
        lang: "İngilizce ve Almanca ya da İspanyolca",
        line: "Haftada en az bir fen dersi laboratuvarda. Her öğrenci her hafta küçük bir projeyi sunar.",
        quote: "Deneyi önce yanlış yapmalarına izin veririz. Doğrusunu kendileri bulunca unutmazlar.",
        who: "Burak Tan, fen bilimleri öğretmeni",
        image: img("ortaokul"),
      },
      lise: {
        name: "Lise",
        range: "Hazırlık-12. sınıf",
        size: "En fazla 18, IB sınıflarında 16",
        lang: "İngilizce, ikinci dil, isteğe bağlı üçüncü",
        line: "Ulusal program ve IB Diploma Programı. Üniversite danışmanlığı 9. sınıfta başlar.",
        quote: "Üniversite tercihini son sınıfa bırakmayız. 9. sınıftan itibaren her öğrenciyle birlikte düşünürüz.",
        who: "Zeynep Arıkan, üniversite danışmanı",
        image: img("lise"),
      },
    } as Record<Kademe, { name: string; range: string; size: string; lang: string; line: string; quote: string; who: string; image: ImageKey }>,
  },

  approach: {
    folio: "§ 04",
    title: "Üç alışkanlık, anaokulundan mezuniyete.",
    imageAlt: "Deftere kurşun kalemle not alan bir el",
    items: [
      {
        title: "Her öğrencinin bir danışmanı var.",
        text: "Danışman öğretmen haftada bir öğrencisiyle birebir görüşür, ayda bir velisini arar. Nottan önce çocuğun nasıl olduğunu konuşuruz.",
      },
      {
        title: "Her hafta bir sunum.",
        text: "5. sınıftan itibaren öğrenciler her hafta küçük bir projeyi sınıfa anlatır. Söz almak zamanla alışkanlık olur.",
      },
      {
        title: "Sanat ve spor, ders programının içinde.",
        text: "Her gün bir saat müzik, görsel sanatlar ya da spor. Kulüpler bunun üstüne gelir, yerine değil.",
      },
    ],
  },

  alumni: {
    folio: "§ 03",
    title: "2026 mezunlarımız",
    intro: "92 mezunumuzun 71'i yurt içinde, 21'i yurt dışında bir üniversiteye yerleşti.",
    tabs: { home: "Yurt içi", abroad: "Yurt dışı" },
    tabsLabel: "Yerleşme bölgesi",
    home: [
      { name: "Boğaziçi Üniversitesi", n: 9 },
      { name: "Koç Üniversitesi", n: 8 },
      { name: "İstanbul Teknik Üniversitesi", n: 7 },
      { name: "Orta Doğu Teknik Üniversitesi", n: 6 },
      { name: "Bilkent Üniversitesi", n: 6 },
      { name: "Sabancı Üniversitesi", n: 5 },
      { name: "Galatasaray Üniversitesi", n: 3 },
      { name: "Hacettepe Üniversitesi Tıp Fakültesi", n: 3 },
    ],
    homeRest: "ve 24 mezunumuz 14 üniversitede daha",
    abroad: [
      { name: "Technische Universität München", n: 3 },
      { name: "University of Toronto", n: 3 },
      { name: "TU Delft", n: 2 },
      { name: "King's College London", n: 2 },
      { name: "Università Bocconi", n: 2 },
      { name: "Maastricht University", n: 2 },
      { name: "University of Edinburgh", n: 2 },
    ],
    abroadRest: "ve 5 mezunumuz 5 üniversitede daha",
    quote: "Tercih listemi üç kez baştan yazdım. Danışmanım üçünde de oturup benimle yeniden düşündü.",
    who: "Ece, 2026 mezunu",
    whoDetail: "Boğaziçi Üniversitesi, Moleküler Biyoloji",
    link: "Üniversite rehberliği nasıl işliyor",
    linkHref: "/revak/kabul/#sss",
  },

  clubs: {
    folio: "§ 05",
    title: "Ders bittiğinde",
    intro: "Otuzdan fazla kulüp ve takım var. Her öğrenci yılda en az birine katılır; çoğu ikiye.",
    items: [
      { name: "Oda orkestrası", range: "4-12. sınıf", image: img("music") },
      { name: "Robotik", range: "5-12. sınıf", image: img("robotics") },
      { name: "Münazara", range: "7-12. sınıf", image: img("debate") },
      { name: "Seramik atölyesi", range: "1-12. sınıf", image: img("ceramics") },
      { name: "Tiyatro", range: "3-12. sınıf", image: img("stage") },
      { name: "Model Birleşmiş Milletler", range: "8-12. sınıf", image: img("library") },
      { name: "Yüzme", range: "Anaokulundan 12. sınıfa", image: img("pool") },
      { name: "Basketbol", range: "3-12. sınıf", image: img("court") },
      { name: "Satranç", range: "1-12. sınıf", image: img("chess") },
    ],
    more: "ve 21 kulüp daha",
  },

  campusPreview: {
    folio: "§ 06",
    title: "Zekeriyaköy'de, ormanın kıyısında 48 dönüm.",
    imageAlt: "Kampüsün avlusu ve çevresindeki binalar",
    facilities: [
      { name: "Yarı olimpik kapalı havuz", text: "Yüzme anaokulundan itibaren ders programında." },
      { name: "Üç katlı kütüphane", text: "38.000 kitap, lise için akşam 19.00'a kadar açık." },
      { name: "Altı fen laboratuvarı", text: "İki öğrenciye bir mikroskop." },
      { name: "420 kişilik sahne", text: "Konserler, oyunlar, mezuniyet." },
    ],
    cta: "Kampüsü keşfedin",
  },

  events: {
    folio: "§ 07",
    title: "Yaklaşan etkinlikler",
    filterLabel: "Etkinlik türü",
    filters: { all: "Tümü", onsite: "Yerinde", online: "Çevrim içi" },
    columns: { date: "Tarih", event: "Etkinlik", where: "Yer ve saat", action: "İşlem" },
    addToCal: "Takvime ekleyin",
    empty: "Bu türde yaklaşan etkinlik yok.",
    items: [
      {
        id: "acik-kapi",
        iso: "2026-10-10",
        day: "10",
        month: "Ekim",
        weekday: "Cumartesi",
        title: "Açık Kapı Günü",
        text: "Kampüs yürüyüşü, açık sınıflar ve kademe koordinatörleriyle sohbet. Kayıt gerekmez.",
        where: "Kampüs, ana giriş",
        time: "10.00-13.00",
        start: "10.00",
        minutes: 180,
        mode: "onsite" as const,
      },
      {
        id: "veli-semineri",
        iso: "2026-10-21",
        day: "21",
        month: "Ekim",
        weekday: "Çarşamba",
        title: "Veli semineri: Ergenlikte ekran ve uyku",
        text: "Psikolojik danışmanımız Dr. Seda Kılınç ile bir saatlik söyleşi ve soru-cevap.",
        where: "Çevrim içi",
        time: "19.00-20.00",
        start: "19.00",
        minutes: 60,
        mode: "online" as const,
      },
      {
        id: "lise-tanitim",
        iso: "2026-11-04",
        day: "4",
        month: "Kasım",
        weekday: "Çarşamba",
        title: "Lise ve IB tanıtım toplantısı",
        text: "Ulusal program ile IB Diploma Programı arasındaki farklar, üniversite rehberliği ve ders seçimi.",
        where: "Çevrim içi",
        time: "18.30-19.30",
        start: "18.30",
        minutes: 60,
        mode: "online" as const,
      },
      {
        id: "bursluluk",
        iso: "2026-11-15",
        day: "15",
        month: "Kasım",
        weekday: "Pazar",
        title: "Bursluluk sınavı",
        text: "Şu an 4-11. sınıfta olan öğrenciler için. %25 ile %100 arasında burs.",
        where: "Kampüs, B Blok",
        time: "10.00-11.30",
        start: "10.00",
        minutes: 90,
        mode: "onsite" as const,
        cta: { label: "Sınava başvurun", href: "/revak/kabul/bursluluk/" },
      },
      {
        id: "kis-konseri",
        iso: "2026-12-18",
        day: "18",
        month: "Aralık",
        weekday: "Cuma",
        title: "Kış konseri",
        text: "Oda orkestrası ve ilkokul korosu. Aday aileler de davetli.",
        where: "Revak Sahnesi",
        time: "19.30-21.00",
        start: "19.30",
        minutes: 90,
        mode: "onsite" as const,
      },
    ],
  },

  voices: {
    folio: "§ 08",
    title: "Velilerimizden",
    items: [
      {
        quote: "Oğlumun matematik öğretmeni, onun neden sessizleştiğini benden önce fark etti. O telefonu unutmuyorum.",
        who: "Aslı D.",
        role: "6. sınıf velisi",
      },
      {
        quote: "Üç çocuğumuz da burada okudu. En büyüğü artık üniversitede ve hâlâ danışman öğretmenine yazıyor.",
        who: "Kerem ve Nil T.",
        role: "Mezun ve lise velisi",
      },
    ],
  },

  faq: {
    folio: "§ 09",
    title: "Velilerin en çok sorduğu sorular",
    intro: "Burada cevabını bulamadığınız her soru için kabul ofisimiz hafta içi 08.30-17.30 arasında telefonda.",
    feeCta: "Ücret bilgisini alın",
    groups: [
      {
        title: "Kabul",
        items: [
          {
            q: "Ön kayıt bir yükümlülük getirir mi?",
            a: "Hayır. Ön kayıt, sizinle bir tanışma görüşmesi planlamamızı sağlar. Kesin kayıt, görüşme ve gözlem gününden sonra, siz karar verdiğinizde yapılır.",
          },
          {
            q: "Yıl ortasında nakil kabul ediyor musunuz?",
            a: "Kontenjanı olan sınıflarda evet. Ön kayıt formunda 2026-2027 ara dönemini seçebilirsiniz; kabul ofisi uygun sınıfları aynı gün bildirir.",
          },
          {
            q: "Üniversite rehberliği nasıl işliyor?",
            a: "9. sınıfta her öğrenciye bir üniversite danışmanı atanır. Yurt içi ve yurt dışı başvurular için ayrı ekiplerimiz var; tercih döneminde veliyle birlikte en az üç görüşme yapılır.",
          },
        ],
      },
      {
        title: "Ücret ve burs",
        items: [
          {
            q: "Ücretleri neden sitede yayımlamıyorsunuz?",
            a: "Ücret kademeye, servis ve yemek tercihine göre değişiyor. Size uyan tabloyu, geçerli indirimlerle birlikte aynı gün gönderiyoruz.",
          },
          {
            q: "Hangi indirimler var?",
            a: "Kardeş indirimi %10, erken kayıt indirimi %7, peşin ödeme indirimi %5. Bursluluk sınavıyla %25 ile %100 arasında burs kazanılabilir.",
          },
        ],
      },
      {
        title: "Servis ve yemek",
        items: [
          {
            q: "Servis hangi semtlere gidiyor?",
            a: "Sarıyer, Beşiktaş, Şişli, Kağıthane, Eyüpsultan, Beykoz ve Üsküdar'a. Kampüs sayfasında semtinizi seçip sabah alınma saatini görebilirsiniz.",
          },
          {
            q: "Yemekleri kim hazırlıyor?",
            a: "Kampüs mutfağında, beslenme uzmanımızın hazırladığı menüyle her gün taze pişiyor. Haftanın menüsü her cuma veli uygulamasında yayımlanır.",
          },
        ],
      },
      {
        title: "Güvenlik ve sağlık",
        items: [
          {
            q: "Kampüse girişler nasıl kontrol ediliyor?",
            a: "Kampüsün tek girişi var. Ziyaretçiler kimlikle kaydolur ve kampüste refakatle dolaşır; öğrenciler veliye kartla teslim edilir.",
          },
          {
            q: "Okulda hemşire var mı?",
            a: "Revirde iki hemşire tam gün görevde, okul doktoru haftada üç gün kampüste. Acil durumlar için en yakın hastaneyle anlaşmamız var.",
          },
        ],
      },
    ],
  },

  closing: {
    title: "Kampüsü görmeden karar vermeyin.",
    text: "Tur yaklaşık bir saat sürer. Sınıfları dolaşır, öğretmenlerle tanışır, sorularınızı kabul ofisine sorarsınız.",
    slotsLabel: "En yakın boş saatler",
    left: (n: number) => (n === 1 ? "son 1 yer" : `${n} yer kaldı`),
    other: "Başka bir gün seçin",
    loading: "Boş saatler yükleniyor",
  },

  footer: {
    contactTitle: "Bize ulaşın",
    routesTitle: "Servis bölgeleri",
    routes: "Sarıyer, Beşiktaş, Şişli, Kağıthane, Eyüpsultan, Beykoz, Üsküdar",
    linksTitle: "Kabul",
    links: [
      { label: "Ön kayıt", href: "/revak/kabul/on-kayit/" },
      { label: "Kampüs turu", href: "/revak/kabul/kampus-turu/" },
      { label: "Bursluluk sınavı", href: "/revak/kabul/bursluluk/" },
      { label: "Ücret bilgisi", href: "/revak/kabul/ucret-bilgisi/" },
    ],
    kvkk: "KVKK aydınlatma metni",
    directions: "Yol tarifi",
    creditsTitle: "Görseller ve yazı karakterleri",
    creditsLead: "Fotoğraflar Pexels lisansıyla kullanılmıştır:",
    fonts: "Yazı karakterleri: Newsreader (Production Type) ve Hanken Grotesk (Alfredo Marco Pradil), SIL Open Font License.",
    note: "Revak Okulları kurgusal bir markadır; bu site rasitburucu.com için hazırlanmış bir tasarım örneğidir. Kişiler, rakamlar ve yerleştirme sonuçları temsilidir.",
    copyright: "© 2026 Revak Okulları",
  },

  kvkk: {
    title: "Kişisel verilerin korunması hakkında aydınlatma metni",
    close: "Kapat",
    body: [
      "Revak Okulları olarak, 6698 sayılı Kişisel Verilerin Korunması Kanunu kapsamında veri sorumlusuyuz. Bu metin, ön kayıt, kampüs turu, bursluluk sınavı ve ücret bilgisi formlarında paylaştığınız bilgileri nasıl kullandığımızı anlatır.",
      "Topladığımız bilgiler: veli adı soyadı, telefon, e-posta; öğrencinin adı soyadı, doğum tarihi, sınıfı ve şu an gittiği okul. Bu formlarda sağlık bilgisi ve kimlik numarası istemeyiz.",
      "Amacımız: başvurunuzu değerlendirmek, sizinle görüşme ve tur planlamak, sınav giriş belgesi hazırlamak ve istediğiniz ücret bilgisini iletmek. Bilgileriniz bu amaçlar dışında kullanılmaz ve üçüncü kişilerle pazarlama amacıyla paylaşılmaz.",
      "Saklama süresi: kesin kayda dönüşmeyen başvurular iki yıl sonra silinir. Etkinlik ve duyuru iletileri yalnızca ayrıca izin verdiyseniz gönderilir; bu izni istediğiniz an geri alabilirsiniz.",
      "Kanunun 11. maddesi kapsamındaki haklarınız için kvkk@revak.k12.tr adresine yazabilirsiniz.",
    ],
  },

  /* ---------------- kampüs ---------------- */

  kampus: {
    metaTitle: "Kampüs ve yaşam | Revak Okulları",
    title: "Bir günün tamamı, tek bir bahçede.",
    intro:
      "Zekeriyaköy'deki kampüsümüz 48 dönüm. Anaokulunun kendi bahçesi, lisenin kendi binası var; kütüphane, sahne, havuz ve yemekhane herkesin.",
    heroAlt: "Kampüs binasının kemerli cephesi",
    facilitiesTitle: "Her tesisin bir dersi var.",
    facilities: [
      { name: "Fen laboratuvarları", text: "Altı laboratuvar, iki öğrenciye bir mikroskop. Ortaokulda haftada en az bir ders laboratuvarda geçer.", image: img("lab") },
      { name: "Kütüphane", text: "Üç katta 38.000 kitap ve sessiz çalışma odaları. Lise öğrencileri akşam 19.00'a kadar kalabilir.", image: img("library") },
      { name: "Sahne ve müzik odaları", text: "420 kişilik sahne, on iki bireysel çalışma odası. Her öğrenci ilkokulda bir çalgıya başlar.", image: img("music") },
      { name: "Spor salonu ve havuz", text: "Yarı olimpik kapalı havuz, iki salon ve açık pist. Yüzme anaokulundan itibaren ders programında.", image: img("pool") },
      { name: "Yemekhane", text: "Kendi mutfağımızda her gün taze pişen üç öğün. Alerji ve diyet listeleri mutfakta ve sınıf öğretmeninde.", image: img("dining") },
      { name: "Atölyeler", text: "Seramik fırını, ahşap ve robotik atölyesi. Dönem boyunca yapılan işler dönem sonunda sergilenir.", image: img("ceramics") },
      { name: "Bahçeler ve orman yolu", text: "Teneffüsler açık havada. Baharda fen dersleri kampüsün orman kıyısında da yapılır.", image: img("garden") },
    ],
    day: {
      title: "Bir gün burada",
      intro: "Servisten inişten eve dönüşe kadar, bir öğrencinin günü saat saat. İlkokul ve lise günleri birbirinden epey farklı.",
      toggleLabel: "Kademe",
      toggle: { ilkokul: "İlkokul", lise: "Lise" },
      railLabel: "Günün saatleri",
      cta: "Bu günü yerinde görün",
      ctaNote: "En yakın boş tur saati seçili olarak açılır.",
      ilkokul: [
        { time: "08.10", title: "Kapıda karşılama", text: "Servisler 08.10'da kampüste. Nöbetçi öğretmen her çocuğu adıyla karşılar.", image: img("kampusHero") },
        { time: "08.40", title: "Okuma saati", text: "Güne yirmi dakikalık okumayla başlarız. Herkes kendi kitabıyla, sınıfın kitaplığından ya da evden.", image: img("ilkokul") },
        { time: "10.20", title: "İngilizce", text: "Ana dili İngilizce olan öğretmenle, dört kişilik gruplarda konuşma çalışması.", image: img("writing") },
        { time: "12.00", title: "Öğle yemeği ve bahçe", text: "Öğretmenler çocuklarla aynı masada yer. Ardından bahçede kırk dakika.", image: img("dining") },
        { time: "13.30", title: "Sanat ya da yüzme", text: "Haftanın iki günü havuzda, üç günü atölyede ya da müzik odasında.", image: img("ceramics") },
        { time: "15.40", title: "Kulüpler ve etüt", text: "Satranç, seramik, orkestra, tiyatro. İsteyen öğrenci ödevini etüt saatinde bitirir.", image: img("chess") },
        { time: "16.30", title: "Servise biniş", text: "Servis kampüsten çıktığında veli uygulaması size haber verir.", image: img("campus") },
      ],
      lise: [
        { time: "07.45", title: "Kütüphane açılır", text: "Erken gelen öğrenciler için lise kütüphanesi ilk dersten önce açık.", image: img("library") },
        { time: "08.40", title: "İlk ders", text: "Ulusal program ve IB dersleri 40 dakikalık bloklar halinde.", image: img("classroom") },
        { time: "10.20", title: "Laboratuvar", text: "Kimya ve biyoloji derslerinin üçte biri laboratuvarda geçer.", image: img("lab") },
        { time: "12.30", title: "Öğle ve kulüp toplantıları", text: "Yemekten sonra münazara ve Model BM kulüpleri kısa toplantılarını yapar.", image: img("debate") },
        { time: "14.00", title: "Danışman saati", text: "Haftada bir, danışman öğretmenle birebir görüşme. Üniversite planı bu saatlerde şekillenir.", image: img("lise") },
        { time: "15.40", title: "Takımlar", text: "Basketbol, yüzme, robotik. Maçlar ve turnuvalar okul takviminde.", image: img("court") },
        { time: "16.30", title: "Servis ya da etüt", text: "Servisler 16.30'da kalkar; kütüphane 19.00'a kadar açık kalır.", image: img("corridor") },
      ],
    },
    transport: {
      title: "Servis bölgeleri",
      intro: "Semtinizi seçin; sabah alınma saatini ve yaklaşık yolculuk süresini görün.",
      label: "Oturduğunuz semt",
      placeholder: "Semt seçin",
      found: (district: string) => `${district} için güzergâhımız var.`,
      pickup: "Sabah alınma",
      pickupNote: "yaklaşık",
      duration: "Yolculuk",
      minutes: (n: number) => `yaklaşık ${n} dakika`,
      features: [
        "Her araçta rehber personel ve emniyet kemeri.",
        "Aracın konumunu veli uygulamasından canlı izlersiniz.",
        "Akşam 16.30 ve etüt sonrası 17.45 olmak üzere iki dönüş.",
      ],
      none: (district: string) => `${district} bölgesine henüz servisimiz yok.`,
      noneText: "Talep bırakın; aynı semtten yeterli aile olduğunda yeni güzergâh açıyoruz.",
      requestLabel: "Cep telefonunuz",
      requestCta: "Talep bırakın",
      requestDone: "Talebinizi aldık. Güzergâh planlandığında sizi arayacağız.",
      districts: [
        { id: "sariyer", name: "Sarıyer", pickup: "07.35", minutes: 25 },
        { id: "besiktas", name: "Beşiktaş", pickup: "07.10", minutes: 45 },
        { id: "sisli", name: "Şişli", pickup: "07.05", minutes: 50 },
        { id: "kagithane", name: "Kağıthane", pickup: "07.15", minutes: 45 },
        { id: "eyupsultan", name: "Eyüpsultan", pickup: "07.20", minutes: 40 },
        { id: "beykoz", name: "Beykoz", pickup: "07.00", minutes: 55 },
        { id: "uskudar", name: "Üsküdar", pickup: "06.55", minutes: 60 },
        { id: "atasehir", name: "Ataşehir", pickup: null, minutes: null },
        { id: "kadikoy", name: "Kadıköy", pickup: null, minutes: null },
        { id: "basaksehir", name: "Başakşehir", pickup: null, minutes: null },
      ] as { id: string; name: string; pickup: string | null; minutes: number | null }[],
    },
    care: {
      title: "Güvenlik, sağlık ve yemek",
      items: [
        { q: "Kampüse kim girebilir?", a: "Kampüsün tek girişi var ve 24 saat görevli bulunur. Ziyaretçiler kimlikle kaydolur, kampüste refakatle dolaşır." },
        { q: "Çocuğum hastalanırsa?", a: "Revirde iki hemşire tam gün görevde, okul doktoru haftada üç gün kampüste. İlaçlar yalnızca veli onayıyla ve kayıt altında verilir." },
        { q: "Alerjisi var, ne yemek yiyecek?", a: "Menüyü beslenme uzmanımız hazırlar. Alerjisi olan her öğrencinin listesi mutfakta ve sınıf öğretmeninde bulunur; tabağı ayrı hazırlanır." },
        { q: "Bir kaygımı kime söyleyeceğim?", a: "Tüm çalışanlarımız çocuk koruma eğitimi alır. Kaygınızı doğrudan paylaşabileceğiniz, bu konudan sorumlu bir öğretmenimiz var." },
      ],
      menuTitle: "Bu haftanın öğle menüsü",
      menuNote: "İlkokul ve üstü. Anaokulu menüsü ayrı hazırlanır.",
      menu: [
        { day: "Pazartesi", dish: "Mercimek çorbası, fırında tavuk, bulgur pilavı, mevsim salatası" },
        { day: "Salı", dish: "Ezogelin çorbası, zeytinyağlı taze fasulye, yoğurt, tam buğday ekmeği" },
        { day: "Çarşamba", dish: "Sebze çorbası, izmir köfte, pirinç pilavı, ayran" },
        { day: "Perşembe", dish: "Tarhana çorbası, fırında levrek, patates püresi, roka salatası" },
        { day: "Cuma", dish: "Yayla çorbası, nohutlu ıspanak, erişte, mevsim meyvesi" },
      ],
    },
    closing: {
      title: "Kampüsü bir saatte görün.",
      text: "Yerinde tur, sınıf ziyareti ve kabul ofisiyle görüşme. Çevrim içi tur da akşam 18.30'a kadar mümkün.",
    },
  },

  /* ---------------- kabul ---------------- */

  kabul: {
    metaTitle: "Kabul | Revak Okulları",
    title: "Başvurudan ilk güne, adım adım.",
    intro:
      "Kabul ofisimiz hafta içi 08.30-17.30 arasında açık. Hangi adımdan başlayacağınızı bilmiyorsanız bir tur planlayın; gerisini birlikte konuşuruz.",
    pathsTitle: "Nereden başlamak istersiniz?",
    paths: [
      { id: "on-kayit", title: "Ön kayıt", text: "Tanışma görüşmesi için ilk adım. Dört dakikada tamamlanır, hiçbir yükümlülük getirmez.", cta: "Ön kayıt yaptırın", href: "/revak/kabul/on-kayit/" },
      { id: "tur", title: "Kampüs turu", text: "Yerinde bir saat ya da çevrim içi yarım saat. Çalışan veliler için akşam 18.30 seçeneği var.", cta: "Tur planlayın", href: "/revak/kabul/kampus-turu/" },
      { id: "burs", title: "Bursluluk sınavı", text: "Şu an 4-11. sınıfta olan öğrenciler için. %25 ile %100 arasında burs.", cta: "Sınava başvurun", href: "/revak/kabul/bursluluk/" },
      { id: "ucret", title: "Ücret bilgisi", text: "Size uyan ücret tablosu ve geçerli indirimler, aynı gün e-postanızda.", cta: "Ücret bilgisini alın", href: "/revak/kabul/ucret-bilgisi/" },
    ],
    processTitle: "Kayıt süreci dört adımda",
    process: [
      { title: "Ön kayıt", text: "Formu doldurduğunuzda kabul ofisi bir iş günü içinde sizi arar ve görüşme saati belirler." },
      { title: "Tanışma görüşmesi", text: "Kabul müdürü ve kademe koordinatörüyle kırk beş dakika. Çocuğunuzu ve beklentilerinizi dinleriz." },
      { title: "Gözlem günü", text: "Çocuğunuz yaşıtlarıyla bir sınıfta yarım gün geçirir. Anaokulu ve ilkokulda oyunla, ortaokul ve lisede kısa bir değerlendirmeyle." },
      { title: "Kesin kayıt", text: "Sonucu üç iş günü içinde bildiririz. Kesin kayıt sözleşmesi kampüste, sizinle birlikte imzalanır." },
    ],
    datesTitle: "Önemli tarihler",
    dates: [
      { date: "10 Ekim", text: "Açık Kapı Günü" },
      { date: "11 Kasım", text: "Bursluluk sınavı son başvuru" },
      { date: "15 Kasım", text: "Bursluluk sınavı" },
      { date: "1 Aralık", text: "2027-2028 kesin kayıtları başlar" },
      { date: "15 Mart", text: "Erken kayıt indirimi sona erer" },
    ],
    burs: {
      title: "Bursluluk sınavı",
      intro: "Şu an 4-11. sınıfta olan öğrenciler girebilir. Sınav 90 dakika sürer; Türkçe, matematik, fen bilimleri, sosyal bilgiler ve İngilizce sorularından oluşur. Soru sayısı sınıfa göre 50 ile 60 arasındadır.",
      countdownLabel: (date: string) => `${date} oturumuna kalan süre`,
      units: { days: "gün", hours: "saat", minutes: "dakika", seconds: "saniye" },
      sessionsTitle: "Oturumlar",
      tiersTitle: "Burs oranları",
      tiersHead: { rank: "Sıralama", rate: "Burs" },
      tiersNote: "Oran, sınıf düzeyindeki sıralamaya göre belirlenir ve öğrenim süresince başarı koşuluyla devam eder.",
      tiers: [
        { rank: "İlk %1", rate: "%100" },
        { rank: "Sonraki %4", rate: "%75" },
        { rank: "Sonraki %10", rate: "%50" },
        { rank: "Sonraki %15", rate: "%25" },
      ],
      sampleTitle: "Örnek sorular",
      sampleIntro: "Sınavın zorluk düzeyini görmek için üç soru.",
      correct: "Doğru.",
      wrong: "Tam değil.",
      samples: [
        {
          tag: "4. sınıf, matematik",
          q: "Bir kırtasiyede 3 defter 45 lira. Aynı defterlerden 5 tanesi kaç lira eder?",
          options: ["60 lira", "65 lira", "75 lira", "90 lira"],
          answer: 2,
          why: "Bir defter 45 ÷ 3 = 15 lira; 5 defter 75 lira eder.",
        },
        {
          tag: "6. sınıf, Türkçe",
          q: "Hangi cümlede \"yüz\" sözcüğü \"bir şeyin dışa bakan tarafı\" anlamında kullanılmıştır?",
          options: ["Havuzda yüz metre yüzdü.", "Kumaşın yüzü daha parlak.", "Yüzünü yıkayıp kahvaltıya indi.", "Onunla yüz yüze konuşmak istedi."],
          answer: 1,
          why: "Kumaşın yüzü, dışa bakan tarafıdır. Diğer cümlelerde sayı, organ ve \"karşı karşıya\" anlamları var.",
        },
        {
          tag: "9. sınıf, İngilizce",
          q: "If it ___ tomorrow, we will cancel the trip.",
          options: ["will rain", "rains", "rained", "would rain"],
          answer: 1,
          why: "Birinci tip koşul cümlesinde \"if\" kısmı geniş zamanla kurulur: If it rains, we will...",
        },
      ],
      cta: "Sınava başvurun",
    },
    fees: {
      title: "Ücretler ve indirimler",
      text: "Ücret; kademeye, servis ve yemek tercihine göre değişir. Size uyan tabloyu geçerli indirimlerle birlikte gönderiyoruz.",
      discounts: [
        { rate: "%10", text: "Kardeş indirimi, ikinci çocuktan itibaren" },
        { rate: "%7", text: "Erken kayıt indirimi, 15 Mart'a kadar" },
        { rate: "%5", text: "Peşin ödeme indirimi" },
      ],
      cta: "Ücret bilgisini alın",
    },
    faqTitle: "Kabulle ilgili sorular",
  },

  /* ---------------- flows ---------------- */

  flows: {
    common: {
      back: "Geri",
      next: "Devam edin",
      close: "Kabul sayfasına dön",
      closeShort: "Kapat",
      step: (i: number, n: number) => `Adım ${i} / ${n}`,
      stepsLabel: "Başvuru adımları",
      plateLabel: "Başvurduğunuz kademe",
      edit: "Düzenle",
      toSummary: "Özete dönün",
      optional: "isteğe bağlı",
      select: "Seçin",
      help: { title: "Sorunuz mu var?", text: "Kabul ofisimiz hafta içi 08.30-17.30 arasında telefonda." },
      phonePrefix: "+90",
      kvkkPre: "",
      kvkkLink: "Aydınlatma metnini",
      kvkkPost: " okudum; başvurum için kişisel verilerimin işlenmesine açık rıza veriyorum.",
      kvkkError: "Devam etmek için aydınlatma metnini onaylayın.",
      marketing: "Etkinlik ve duyurulardan e-posta ya da SMS ile haberdar olmak istiyorum.",
      errors: {
        phone: "Cep telefonu 5 ile başlamalı ve 10 haneli olmalı.",
        email: "E-posta adresini kontrol edin; örneğin ad@alanadi.com",
        choose: "Bir seçenek belirleyin.",
      },
      fields: {
        veliAd: "Adınız soyadınız",
        telefon: "Cep telefonunuz",
        eposta: "E-posta adresiniz",
      },
      fieldErrors: {
        veliAd: "Adınızı ve soyadınızı yazın.",
      },
      kademe: { anaokulu: "Anaokulu", ilkokul: "İlkokul", ortaokul: "Ortaokul", lise: "Lise" } as Record<Kademe, string>,
      kademeHint: { anaokulu: "3-5 yaş", ilkokul: "1-4. sınıf", ortaokul: "5-8. sınıf", lise: "Hazırlık-12" } as Record<Kademe, string>,
      siniflar: {
        anaokulu: [
          { id: "3y", label: "3 yaş grubu", age: [3, 3] },
          { id: "4y", label: "4 yaş grubu", age: [4, 4] },
          { id: "5y", label: "5 yaş grubu", age: [5, 5] },
        ],
        ilkokul: [
          { id: "1", label: "1. sınıf", age: [5, 7] },
          { id: "2", label: "2. sınıf", age: [6, 8] },
          { id: "3", label: "3. sınıf", age: [7, 9] },
          { id: "4", label: "4. sınıf", age: [8, 10] },
        ],
        ortaokul: [
          { id: "5", label: "5. sınıf", age: [9, 11] },
          { id: "6", label: "6. sınıf", age: [10, 12] },
          { id: "7", label: "7. sınıf", age: [11, 13] },
          { id: "8", label: "8. sınıf", age: [12, 14] },
        ],
        lise: [
          { id: "hz", label: "Hazırlık", age: [13, 15] },
          { id: "9", label: "9. sınıf", age: [13, 15] },
          { id: "10", label: "10. sınıf", age: [14, 16] },
          { id: "11", label: "11. sınıf", age: [15, 17] },
          { id: "12", label: "12. sınıf", age: [16, 18] },
        ],
      } as Record<Kademe, SinifOption[]>,
    },

    onKayit: {
      metaTitle: "Ön kayıt | Revak Okulları",
      name: "Ön kayıt",
      steps: ["Sınıf", "Öğrenci", "Veli", "Onay"],
      helpNote: "Ön kayıt hiçbir yükümlülük getirmez. Kesin kayıt kararı, tanışma görüşmesinden sonra sizindir.",
      s1: {
        title: "Hangi sınıf için başvuruyorsunuz?",
        yil: "Akademik yıl",
        yillar: [
          { id: "2027-2028", label: "2027-2028", hint: "Eylül 2027'de başlar" },
          { id: "2026-2027", label: "2026-2027 ara dönem", hint: "Şubat 2027'de başlar" },
        ],
        kademe: "Kademe",
        sinif: "Sınıf",
        sinifPick: "Önce kademe seçin.",
        errors: { yil: "Akademik yılı seçin.", kademe: "Kademeyi seçin.", sinif: "Sınıfı seçin." },
      },
      s2: {
        title: "Çocuğunuzu tanıyalım.",
        ad: "Adı",
        soyad: "Soyadı",
        dogum: "Doğum tarihi",
        okul: "Şu an gittiği okul",
        okulHintOpt: "Anaokulu için isteğe bağlı",
        ingilizce: "İngilizce düzeyi",
        seviyeler: ["Başlangıç", "Orta", "İleri", "Emin değilim"],
        kardes: "Kardeşi Revak'ta okuyor",
        ozel: "Görüşmede konuşmak istediğimiz özel bir durum var",
        ozelHint: "Ayrıntıyı görüşmede sizden dinleriz; sağlık bilgisi bu formda istenmez.",
        ageWarn: "Seçtiğiniz sınıf için yaş aralığının dışında görünüyor. Görüşmede birlikte değerlendiririz.",
        errors: {
          ad: "Çocuğunuzun adını yazın.",
          soyad: "Çocuğunuzun soyadını yazın.",
          dogum: "Doğum tarihini girin.",
          dogumRange: "Doğum tarihini kontrol edin.",
          okul: "Şu an gittiği okulu yazın.",
        },
      },
      s3: {
        title: "Size nasıl ulaşalım?",
        yakinlik: "Çocuğa yakınlığınız",
        yakinliklar: ["Anne", "Baba", "Vasi"],
        kanal: "Tercih ettiğiniz iletişim",
        kanallar: ["Telefon", "E-posta", "WhatsApp"],
        saat: "Aranmak için uygun saat",
        saatler: ["09.00-12.00", "12.00-15.00", "15.00-18.00", "18.00-20.00"],
        ikinci: "İkinci veliyi ekleyin",
        ikinciKaldir: "İkinci veliyi kaldırın",
        ikinciAd: "İkinci velinin adı soyadı",
        ikinciTel: "İkinci velinin cep telefonu",
        errors: { yakinlik: "Yakınlığınızı seçin.", ikinciAd: "İkinci velinin adını yazın." },
      },
      s4: {
        title: "Bilgilerinizi kontrol edin.",
        sections: { sinif: "Sınıf", ogrenci: "Öğrenci", veli: "Veli" },
        yes: "Evet",
        submit: "Ön kaydı tamamlayın",
      },
      done: {
        title: "Ön kaydınız alındı.",
        ref: "Başvuru numaranız",
        text: (name: string, channel: string) =>
          `${name} için kabul ofisimiz bir iş günü içinde ${channel} size ulaşacak.`,
        channel: { Telefon: "telefonla", "E-posta": "e-postayla", WhatsApp: "WhatsApp'tan" } as Record<string, string>,
        nextTitle: "Sırada ne var",
        next: [
          "Kabul ofisi sizi arar ve görüşme saatini birlikte belirleriz.",
          "Tanışma görüşmesi: kırk beş dakika, kampüste ya da çevrim içi.",
          "Gözlem günü: çocuğunuz yaşıtlarıyla yarım gün geçirir.",
          "Kesin kayıt: karar sizindir, acele etmeyiz.",
        ],
        tour: "Kampüs turu da planlayın",
        tourText: "Bilgileriniz hazır; yalnızca gün ve saat seçmeniz yeterli.",
        burs: "Bursluluk sınavına da başvurun",
        bursText: "Çocuğunuzun sınıfı sınava girmeye uygun.",
      },
    },

    tur: {
      metaTitle: "Kampüs turu | Revak Okulları",
      name: "Kampüs turu",
      steps: ["Tur türü", "Gün ve saat", "İletişim"],
      s1: {
        title: "Kampüsü nasıl görmek istersiniz?",
        tur: "Tur türü",
        types: {
          yerinde: { label: "Yerinde tur", text: "Yaklaşık 60 dakika. Kampüs yürüyüşü, bir sınıf ziyareti ve kabul ofisiyle görüşme." },
          cevrimici: { label: "Çevrim içi tur", text: "30 dakika, canlı ve görüntülü. Akşam 18.30 seçeneği de var." },
        },
        kademeler: "İlgilendiğiniz kademeler",
        errors: { tur: "Tur türünü seçin.", kademeler: "En az bir kademe seçin." },
      },
      s2: {
        title: "Size uyan günü seçin.",
        day: "Gün",
        time: "Saat",
        parts: { sabah: "Sabah", ogleden: "Öğleden sonra", aksam: "Akşam" },
        left: (n: number) => (n === 1 ? "son 1 yer" : `${n} yer kaldı`),
        full: "Dolu",
        closed: "Kapalı",
        holiday: "Tatil",
        pickDay: "Önce bir gün seçin.",
        see: "Özellikle görmek istedikleriniz",
        seeOptions: ["Fen laboratuvarları", "Kütüphane", "Spor salonu ve havuz", "Sahne ve müzik odaları", "Yemekhane", "Servis ve güvenlik"],
        errors: { day: "Bir gün seçin.", time: "Bir saat seçin." },
      },
      s3: {
        title: "Sizi kimin adına bekleyelim?",
        kisi: "Kaç kişi geleceksiniz?",
        less: "Bir kişi azaltın",
        more: "Bir kişi ekleyin",
        cocuk: "Çocuğum da gelecek",
        cocukHint: "Tur sırasında çocuklar bir öğretmenimizle atölyede vakit geçirir.",
        plaka: "Araç plakası",
        plakaHint: "Güvenlik girişinde adınız hazır olur.",
        submit: "Turu planlayın",
      },
      summary: {
        title: "Tur özeti",
        type: "Tür",
        date: "Gün",
        time: "Saat",
        length: "Süre",
        minutes: (n: number) => `${n} dakika`,
        price: "Ücretsiz",
        empty: "Seçim yapılmadı",
      },
      done: {
        title: (name: string) => (name ? `Görüşmek üzere, ${name}.` : "Görüşmek üzere."),
        text: "Turunuz planlandı. Bir gün önce kısa bir hatırlatma mesajı gönderiyoruz.",
        card: "Kampüs turu",
        meet: "Buluşma noktası",
        meetOnsite: "Ana giriş, Revak Kapısı",
        meetOnline: "Görüntülü görüşme bağlantısı turdan bir gün önce e-postanıza gelir.",
        host: "Sizi karşılayacak",
        hostName: "Selin Aksoy, kabul ofisi",
        guests: (n: number) => (n === 1 ? "1 kişi" : `${n} kişi`),
        ics: "Takvime ekleyin",
        directions: "Yol tarifi",
        change: "Saati değiştirin",
        icsTitle: "Revak Okulları kampüs turu",
        icsTitleOnline: "Revak Okulları çevrim içi tur",
        icsDesc: "Sizi karşılayacak: Selin Aksoy, kabul ofisi. Telefon: 0212 000 19 87",
        location: "Revak Okulları, Çamlık Yolu No: 12, Zekeriyaköy, Sarıyer, İstanbul",
        onKayit: "Ön kaydı da şimdi yaptırın",
      },
    },

    burs: {
      metaTitle: "Bursluluk sınavı başvurusu | Revak Okulları",
      name: "Bursluluk sınavı",
      steps: ["Oturum", "Aday ve veli", "Onay"],
      helpNote: "Sınava başvuru ücretsizdir. Sonuçlar sınavdan sonraki on gün içinde veliye bildirilir.",
      s1: {
        title: "Öğrenciniz şu an kaçıncı sınıfta?",
        sinif: "Şu anki sınıfı",
        sinifLabel: (n: number) => `${n}. sınıf`,
        oturum: "Oturum",
        pickGrade: "Sınıfı seçtiğinizde uygun oturumlar burada listelenir.",
        none: "Bu sınıf için başvurusu açık oturum kalmadı. Bir sonraki dönem için ön kayıt yaptırabilirsiniz.",
        deadline: (d: string) => `Son başvuru ${d}`,
        left: (n: number) => `${n} kontenjan kaldı`,
        few: "Kontenjan azalıyor",
        full: "Kontenjan doldu",
        closed: "Başvurular kapandı",
        place: "Revak Kampüsü",
        errors: { sinif: "Sınıfı seçin.", oturum: "Bir oturum seçin." },
      },
      s2: {
        title: "Aday ve veli bilgileri",
        adayAd: "Adayın adı",
        adaySoyad: "Adayın soyadı",
        okul: "Şu an gittiği okul",
        idNote: "Kimlik numarası bu formda istenmez. Sınav günü girişte adayın kimlik kartını ya da öğrenci belgesini yanınızda getirin.",
        errors: { adayAd: "Adayın adını yazın.", adaySoyad: "Adayın soyadını yazın.", okul: "Şu an gittiği okulu yazın." },
      },
      s3: {
        title: "Son bir kontrol.",
        sections: { oturum: "Oturum", aday: "Aday ve veli" },
        rulesPre: "",
        rulesLink: "Sınav şartnamesini",
        rulesPost: " okudum ve kabul ediyorum.",
        rulesError: "Başvuru için sınav şartnamesini onaylayın.",
        submit: "Başvuruyu tamamlayın",
      },
      rules: {
        title: "Bursluluk sınavı şartnamesi",
        body: [
          "Sınava yalnızca 2026-2027 öğretim yılında 4-11. sınıfta okuyan öğrenciler girebilir. Her öğrenci bir öğretim yılında bir oturuma katılabilir.",
          "Adaylar giriş saatinde (09.30) kampüste olmalıdır. 10.15'ten sonra salona aday alınmaz; sınavın ilk 30 dakikasında salondan çıkılmaz.",
          "Adayın yanında kimlik kartı ya da öğrenci belgesi bulunmalıdır. Kurşun kalem ve silgi dışında araç kullanılmaz; cep telefonları salon girişinde teslim alınır.",
          "Burs oranı, aynı sınıf düzeyindeki adaylar arasındaki sıralamaya göre belirlenir. Sonuçlar sınavdan sonraki on gün içinde veliye bildirilir.",
          "Kazanılan burs, kesin kayıt yapılması ve her yıl sonunda ağırlıklı ortalamanın 80 ve üzeri olması koşuluyla öğrenim süresince devam eder.",
        ],
      },
      done: {
        title: "Sınav giriş belgeniz hazır.",
        text: "Belgeyi yazdırabilir ya da telefonunuzda gösterebilirsiniz. Bir kopyası e-postanıza da gönderildi.",
        card: "Bursluluk sınavı giriş belgesi",
        candidate: "Aday",
        number: "Aday numarası",
        grade: "Sınıf",
        session: "Oturum",
        room: "Salon",
        entry: "Giriş saati",
        start: "Sınav başlangıcı",
        place: "Revak Okulları, Zekeriyaköy, Sarıyer",
        print: "Yazdırın",
        ics: "Takvime ekleyin",
        note: "Sınav günü yanınızda kurşun kalem, silgi ve adayın kimlik kartı ya da öğrenci belgesi olsun.",
        icsTitle: "Revak Okulları bursluluk sınavı",
        onKayit: "Ön kaydı da yaptırın",
      },
    },

    ucret: {
      metaTitle: "Ücret bilgisi | Revak Okulları",
      name: "Ücret bilgisi",
      title: "Ücret bilgisini alın.",
      intro: "Size uyan ücret tablosunu, geçerli indirimlerle birlikte gönderelim.",
      kademe: "Kademe",
      yil: "Akademik yıl",
      yillar: ["2027-2028", "2026-2027 ara dönem"],
      kanal: "Nasıl ulaşalım?",
      kanallar: { email: "Tabloyu e-postayla gönderin", phone: "Arayın, anlatın" },
      submit: "Ücret bilgisini alın",
      errors: { kademe: "Kademeyi seçin.", kanal: "Size nasıl ulaşacağımızı seçin." },
      asideTitle: "Ücreti düşüren seçenekler",
      aside: [
        { rate: "%10", text: "Kardeş indirimi" },
        { rate: "%7", text: "15 Mart'a kadar erken kayıt" },
        { rate: "%5", text: "Peşin ödeme" },
        { rate: "%25-100", text: "Bursluluk sınavıyla burs" },
      ],
      asideLink: "Bursluluk sınavı hakkında",
      done: {
        title: "Talebiniz alındı.",
        email: (e: string) => `Ücret tablosu bugün mesai bitmeden ${e} adresinde olacak.`,
        phone: "Kabul ofisimiz bugün içinde sizi arayacak.",
        tour: "Bu arada kampüsü görmek isterseniz",
        tourCta: "Tur planlayın",
      },
    },
  },
};

export type RevakCopy = typeof tr;
