// Every Turkish string of the Kalemkâr concept. Pages and components read from
// here; nothing is typed into the markup.
//
// Durum: metinler Raşit’in onayını bekliyor (plan §6 önerileri temel alındı).
// Kalemkâr ve şef Leman Darcan hayalidir. Fiyatlar ve doluluk örnektir.

const BASE = "/kalemkar";

export const tr = {
  base: BASE,
  meta: {
    title: "Kalemkâr | Gaziantep’te tek menülü akşam sofrası (konsept)",
    description:
      "Kalemkâr, Gaziantep Bey Mahallesi’nde her mevsim tek bir akşam menüsü yazan hayali bir restoran. Konsept çalışma: fiyatlar ve doluluk örnektir.",
    menuTitle: "Güz sofrası | Kalemkâr (konsept)",
    menuDescription: "Dokuz tabaklık güz menüsü, alerjen tablosu, kısa sofra ve tezgâh menüsü farkları, ürünlerin geldiği yerler.",
    bookTitle: "Masanızı ayırın | Kalemkâr (konsept)",
    bookDescription: "Akşamınızı kurun: deneyim, kişi, akşam, saat ve menü. Konsept çalışma, hiçbir bilgi gönderilmez.",
    inviteTitle: "Özel davet | Kalemkâr (konsept)",
    inviteDescription: "Özel oda ya da evin tamamı için talep: 8 ile 34 kişi arası sofralar.",
    notFoundTitle: "Bu tabak menüde yok | Kalemkâr (konsept)",
  },
  skip: "İçeriğe geç",
  strip: {
    text: "Konsept çalışma. Kalemkâr hayali bir restorandır; fiyatlar ve doluluk örnektir, formlar hiçbir yere gönderilmez.",
    link: "rasitburucu.com",
    href: "https://rasitburucu.com/tr",
  },
  brand: { name: "Kalemkâr", word: "KALEMKÂR", home: "Kalemkâr ana sayfa", place: "Gaziantep, Bey Mahallesi" },
  nav: {
    label: "Ana menü",
    items: [
      { label: "Sofra", href: `${BASE}/sofra/` },
      { label: "Şef", href: `${BASE}/#sef` },
      { label: "Ev", href: `${BASE}/#ev` },
      { label: "Özel davet", href: `${BASE}/ozel-davet/` },
    ],
    cta: "Masanızı ayırın",
    menu: "Menü",
    close: "Kapat",
  },
  mobileBar: { label: "Hızlı rezervasyon", cta: "Masa ayır", call: "Ara" },
  sample: "örnek",
  sampleLong: "Örnek fiyat (konsept)",

  hero: {
    title: "Antep’in sofrası, dokuz tabakta.",
    sub: "Her mevsim tek bir akşam menüsü yazıyoruz. Bu güz sofrada Nizip’in yeni zeytinyağı, Araban’ın fıstığı ve bahçeden son patlıcanlar var.",
    sentenceLabel: "Hızlı masa arama",
    forWord: "için",
    eveningWord: "akşamı",
    peopleLabel: "Kişi sayısı",
    dayLabel: "Akşam",
    dayLoading: "bir akşam",
    submit: "Masalara bak",
    free: "Bu hafta boş:",
    freeNone: "Bu hafta boş oturum kalmadı. Gelecek haftaya bakın.",
    facts: "Her akşam tek menü: dokuz tabak, üç saat, on bir masa.",
  },

  service: {
    title: "Bu mevsim sofrada",
    sub: "Menü mevsimle değişir. Bir ürün tarladan kalkınca sofradan da kalkar.",
    of: "/",
    next: "Sonraki tabak",
    restart: "Baştan servis",
    fromLabel: "Nereden",
    pairingLabel: "Alkolsüz eşleşme",
    allMenu: "Menünün tamamı",
    book: "Bu menüye masa ayırın",
    status: (n: number, name: string) => `${n}. tabak servis edildi: ${name}`,
  },

  chef: {
    title: "Dedesinin dükkânından iki sokak ötede",
    name: "Şef Leman Darcan",
    paras: [
      "Leman Darcan, Bakırcılar Çarşısı’nda sini kazıyan dedesinin dükkânında büyüdü. Kalemin bakırda nasıl yol açtığını, bir desenin bir haftada nasıl tamamlandığını orada öğrendi.",
      "On iki yıl İstanbul’da ve Lyon’da mutfaklarda çalıştı, sonra Antep’e döndü. Dükkânın arka sokağındaki on dokuzuncu yüzyıldan kalma taş evi restorana çevirdi.",
      "Her mevsim yöre üreticilerinden gelen ürünle tek bir akşam menüsü yazıyor. Tabaklar dedesinin kazıdığı sinilerde geliyor; sini kenarındaki yazı o mevsimin ürünlerini sayıyor.",
    ],
    quote: "Dedem bakıra ne kazıyacağını önceden çizmezdi, kalemle ne kadar gidebileceğini bilirdi. Menüyü ben de öyle yazıyorum: bahçede ne varsa, o kadar.",
    quoteBy: "Leman Darcan",
    capHands: "Servisten önce son dokunuş",
    capCopper: "Bakırcılar Çarşısı’nda kalem kazıma",
  },

  house: {
    title: "Taş ev, üç sofra",
    sub: "Avlunun çevresinde üç ayrı oturma var. Planda birini seçin, rezervasyona o sofrayla geçin.",
    planLabel: "Kalemkâr’ın kat planı. Bir alan seçin.",
    bookThis: "Bu sofrayla rezervasyon",
    north: "K",
    areas: {
      salon: {
        name: "Salon",
        body: "On bir masa, yüksek tavanlı eski misafir odasında. Pencereler avluya bakar.",
        meta: "1–6 kişi. Sofra (9 tabak) ya da Kısa sofra (6 tabak).",
      },
      tezgah: {
        name: "Şefin tezgâhı",
        body: "Şefin tezgâhında sekiz kişi, mutfağın tam karşısında oturur. Her tabağı onu hazırlayan elden alırsınız.",
        meta: "1–4 kişi. Tek oturum 19.30, 12 tabak.",
      },
      ozel: {
        name: "Özel oda",
        body: "Özel odamız on dört kişiyi ağırlar. İş yemeği, nişan sofrası, sessiz bir kutlama: menüyü birlikte yazalım.",
        meta: "8–14 kişi, talep ile. Evin tamamı 34 kişiye kadar.",
      },
      avlu: {
        name: "Avlu",
        body: "Hava izin verdiğinde ilk iki tabak avluda, havuzun başında gelir. Sonra içeri geçilir.",
        meta: "Ayrıca rezerve edilmez.",
      },
    },
    kitchen: "Mutfak",
    pool: "Havuz",
    entrance: "Giriş",
  },

  know: {
    title: "Gelmeden önce",
    items: [
      { q: "Depozito", a: "Rezervasyonda kişi başı 1.500 TL depozito alınır ve hesabınızdan düşülür." },
      { q: "İptal ve değişiklik", a: "48 saat öncesine kadar ücretsiz iptal. Sonrasında depozito iade edilmez; tarihi bir kez ücretsiz değiştirebilirsiniz." },
      { q: "Geç kalma", a: "Masanızı 20 dakika bekletiriz. Gecikecekseniz lütfen arayın." },
      { q: "Kıyafet", a: "Özel bir kural yok." },
      { q: "Çocuklar", a: "Akşam menüsü 12 yaş ve üzeri içindir. Daha küçük misafirler için bizi arayın." },
      { q: "Alerji ve diyet", a: "Fıstık bu şehrin imzası. Alerjiniz varsa önceden söyleyin, size ayrı bir sofra kuralım. Menü tam vegan uyarlanamıyor; sebze ağırlıklı bir sofra için 72 saat önceden haber verin." },
      { q: "Erişilebilirlik", a: "Salon ve avlu katı tekerlekli sandalyeye uygun. Tezgâh tabureli ve yüksek; özel oda üç basamakla iner." },
      { q: "İçecekler", a: "Her tabak için alkolsüz bir eşleşme hazırlıyoruz: şıra, demleme, şerbet ve ev yapımı ekşimeler. Kişi başı 1.900 TL." },
    ],
  },

  opening: {
    title: (month: string, openDay: string) => `${month} sofrası ${openDay} açılıyor`,
    body: "Rezervasyonlar her ayın ilk günü saat 10.00’da bir sonraki ay için açılır.",
    left: "Açılmasına",
    units: { days: "gün", hours: "saat", minutes: "dakika" },
    open: "Rezervasyonlar açık.",
    notify: "Açılınca haber ver",
    notifySubject: (month: string) => `${month} rezervasyonları açılınca haber verin`,
    notifyBody: "Merhaba, rezervasyonlar açıldığında bana bu adresten haber verir misiniz?",
  },

  contact: {
    address: ["Bey Mahallesi, Şahinbey", "Gaziantep"],
    walk: "Bakırcılar Çarşısı’na beş dakika yürüme",
    phone: "+90 342 000 00 00",
    phoneHref: "tel:+903420000000",
    email: "masa@kalemkar.example",
    hours: "Çarşamba–Pazar 18.00–24.00. Pazartesi ve salı kapalı.",
    mapsHref: "https://www.openstreetmap.org/search?query=Bey%20Mahallesi%20%C5%9Eahinbey%20Gaziantep",
    directions: "Haritada aç",
  },

  footer: {
    visit: "Ziyaret",
    reach: "Ulaşın",
    pages: "Sayfalar",
    credits: "Görseller ve yazı tipleri",
    creditsNote: "Yemek ve mekân fotoğrafları Pexels’ten, lisansı sayfalarından okundu. Bakır sini ve tepsi bu çalışma için Blender’da modellendi.",
    note: "Kalemkâr, rasitburucu.com için hazırlanmış bir konsept çalışmadır. Restoran, şef, fiyatlar, doluluk ve alıntılar hayalidir.",
    links: [
      { label: "Güz sofrası", href: `${BASE}/sofra/` },
      { label: "Rezervasyon", href: `${BASE}/rezervasyon/` },
      { label: "Özel davet", href: `${BASE}/ozel-davet/` },
    ],
  },

  menuPage: {
    title: "Güz sofrası",
    range: "Ekim – Aralık",
    intro: "Dokuz tabak, yaklaşık üç saat. Menü haftada bir küçük değişir; ürün bitince tabak da değişir.",
    priceLine: "Kişi başı, KDV dahil, servis ücreti yok.",
    variantsTitle: "Üç sofra",
    variants: {
      sofra: "Salonda, 18.30, 21.00 ve 21.30 oturumlarında.",
      kisa: "Salonda, yalnız erken oturumlarda (18.30 ve 19.00). İşaretli altı tabak.",
      tezgah: "Şefin tezgâhında, 19.30 tek oturum. Dokuz tabağa tezgâhta hazırlanan üç tabak eklenir.",
    },
    shortMark: "Kısa sofrada",
    counterTitle: "Yalnız tezgâhta",
    allergenTitle: "Alerjenler",
    allergenNote: "Tabloda her tabağın içerdiği alerjenler var. Mutfakta Antep fıstığı her gün kullanılır; ciddi bir fıstık alerjiniz varsa rezervasyondan önce bizi arayın.",
    allergenNone: "Bu tabakta listelenen alerjen yok",
    tableCaption: "Güz sofrası alerjen tablosu: satırlarda tabaklar, sütunlarda on dört alerjen.",
    dishCol: "Tabak",
    contains: "içerir",
    pairingTitle: "Alkolsüz eşleşme",
    pairingBody: "Her tabağın yanında küçük bir bardak: şıra, demleme, şerbet ya da ev yapımı bir ekşime. Kişi başı 1.900 TL.",
    sourcesTitle: "Ürünler nereden geliyor",
    sourcesBody: "Menünün çoğu şehrin bir saatlik çevresinden geliyor. Halkalar Bey Mahallesi’nden kuş uçuşu uzaklığı gösterir.",
    mapLabel: "Gaziantep ve çevresi; ürünlerin geldiği ilçeler",
    pastTitle: "Geçen mevsim",
    pastBody: "Yaz sofrası 30 Eylül’de kalktı.",
    past: ["Domates ve karpuz, beyaz peynir", "Taze bakla, yoğurt", "Kabak çiçeği dolması", "Közde mısır, isot", "Dut ve kaymak"],
    book: "Bu menüye masa ayırın",
  },

  // Approximate road-free distances from Bey Mahallesi (km) and compass bearing (degrees).
  sources: [
    { key: "oguzeli", name: "Oğuzeli", what: "Firik, domates", km: 24, deg: 150 },
    { key: "nizip", name: "Nizip", what: "İlk sıkım zeytinyağı", km: 46, deg: 98 },
    { key: "yavuzeli", name: "Yavuzeli", what: "Kuzu, üzüm pekmezi", km: 50, deg: 66 },
    { key: "araban", name: "Araban", what: "Antep fıstığı, ağustos hasadı", km: 62, deg: 40 },
  ],
  sourcesCenter: "Kalemkâr",
  sourcesRings: ["20 km", "40 km", "60 km"],

  flow: {
    title: "Akşamınızı kurun",
    sub: "Seçtikçe sini sizin masanıza dönüşür.",
    close: "Vazgeç",
    back: "Geri",
    next: "Devam",
    step: (n: number, total: number) => `Adım ${n} / ${total}`,
    perPerson: "kişi başı",
    total: "Toplam",
    summaryLabel: "Seçimleriniz",
    summaryEmpty: "Henüz seçim yok.",
    sum: { where: "Masa", day: "Akşam", time: "Saat", menu: "Menü", notes: "Notlar", pairing: "alkolsüz eşleşme", guestNotes: (n: number) => `${n} misafir` },
    steps: ["Deneyim", "Akşam", "Saat", "Misafirler", "İletişim", "Onay"],

    experience: {
      title: "Nerede oturmak istersiniz?",
      options: {
        salon: { name: "Salon", meta: "1–6 kişi. Sofra ya da Kısa sofra." },
        tezgah: { name: "Şefin tezgâhı", meta: "1–4 kişi. Tek oturum 19.30, 12 tabak." },
        ozel: { name: "Özel oda", meta: "8–14 kişi, talep ile." },
      },
      peopleTitle: "Kaç kişisiniz?",
      plus: "7+",
      solo: "Yalnız gelenler için tezgâhı öneririz; mutfakla sohbet edersiniz.",
      soloCta: "Tezgâha geç",
      counterMax: "Tezgâh en fazla 4 kişi.",
      group: "Bu kadar kalabalık bir grupta salon bölünür. Size özel oda kuralım.",
      groupCta: "Özel davete geç",
      whole: "15 kişiden kalabalık gruplar için evin tamamını kiralayabilirsiniz.",
      wholeCta: "Evin tamamı için talep",
      ozel: "Özel oda menüsü şefle birlikte yazılır, bu yüzden talep formuyla ilerliyoruz. Seçimleriniz forma taşınır.",
      ozelCta: "Özel davet formuna geç",
      kids: "Akşam menüsü 12 yaş ve üzeri içindir. Daha küçük misafirler için bizi arayın.",
      howMany: "Kişi sayısı",
    },

    date: {
      title: "Hangi akşam?",
      legend: { bos: "Boş", az: "Az kaldı", dolu: "Dolu", kapali: "Kapalı" },
      closed: "Kapalı",
      locked: (when: string) => `${when} 10.00’da açılır`,
      full: "Bu akşam dolu.",
      nearest: "En yakın boş akşamlar:",
      waitlist: "Bekleme listesine yazılın",
      sameDay: "Bu akşam için online rezervasyon 14.00’te kapandı. Bizi arayın, yer varsa ayıralım.",
      special: "31 Aralık’ta ayrı bir yılbaşı sofrası var; özel davet olarak alıyoruz.",
      specialCta: "Yılbaşı sofrası için talep",
      chosen: "Seçilen akşam",
      sim: "Doluluk örnektir.",
      monthLocked: "Henüz açılmadı",
      pick: "Lütfen bir akşam seçin.",
    },

    time: {
      title: "Saat ve menü",
      seatingSalon: "Salon oturumları",
      seatingCounter: "Tezgâh oturumu",
      left: (n: number, unit: string) => (n === 1 ? `son ${unit}` : `son ${n} ${unit}`),
      unitTable: "masa",
      unitSeat: "tabure",
      full: "dolu",
      shortOnly: "yalnız Kısa sofra",
      notShort: "Kısa sofra yalnız erken oturumda",
      notSeats: "bu kadar kişiye yer yok",
      menuTitle: "Menü",
      counterMenu: "Tezgâhta menü tek: 12 tabak.",
      pairing: "Alkolsüz eşleşme ekle",
      pairingNote: "Her tabağa bir bardak: şıra, demleme, şerbet, ekşime.",
      cleared: (t: string) => `${t} oturumu yeni seçiminize uymadığı için kaldırıldı. Lütfen yeniden saat seçin.`,
      waitlist: "Bu saat dolu. Bekleme listesine yazılın",
      pick: "Lütfen bir saat seçin.",
    },

    guests: {
      title: "Misafirleriniz",
      sub: "Her kuver için ayrı not bırakabilirsiniz. İşaretlediğiniz misafirin kuverine sinide yeşil bir işaret düşer.",
      guest: (n: number) => `${n}. misafir`,
      name: "Ad (isteğe bağlı)",
      notes: "Alerji ve diyet",
      other: "Diğer notu",
      otherPh: "Örn. kişniş yemiyor",
      chips: ["Gluten", "Süt", "Fıstık ve kuruyemiş", "Susam", "Yumurta", "Kabuklu deniz ürünü", "Vejetaryen", "Hamilelik", "Vegan", "Diğer"],
      pistachio:
        "Güz menüsünde dört tabak fıstık içerir. Size ayrı bir sofra hazırlarız, ancak mutfakta fıstık kullanılır. Ciddi bir alerjiniz varsa lütfen bizi arayın.",
      vegan: "Menü tam vegan uyarlanamıyor. Sebze ağırlıklı bir sofra için 72 saat önceden haber verin.",
      late: "Akşamınıza 48 saatten az kaldı. Alternatif tabak için lütfen bizi arayın.",
      occasion: "Özel bir gün mü?",
      occasions: ["Doğum günü", "Yıl dönümü", "İş yemeği", "Diğer"],
      noteLabel: "Mutfağa notunuz (isteğe bağlı)",
      access: "Tekerlekli sandalye: salon ve avlu katı uygun. Tezgâh tabureli ve yüksek.",
    },

    contact: {
      title: "İletişim ve kurallar",
      name: "Ad soyad",
      phone: "Cep telefonu",
      phonePrefix: "+90",
      email: "E-posta",
      errName: "Adınızı ve soyadınızı yazın.",
      errPhone: "5 ile başlayan 10 haneli bir numara yazın.",
      errEmail: "Geçerli bir e-posta adresi yazın.",
      errAgree: "Devam etmek için kuralları onaylayın.",
      policyTitle: "Kurallar",
      policy: [
        "Depozito kişi başı 1.500 TL, hesabınızdan düşülür.",
        "48 saat öncesine kadar ücretsiz iptal. Sonrasında depozito iade edilmez.",
        "Masanızı 20 dakika bekletiriz.",
        "Kıyafet için özel bir kural yok.",
      ],
      agree: "Kuralları okudum, kabul ediyorum.",
      today: "Bugün alınacak",
      deposit: "Depozito",
      pay: "Ödeme sayfasına geç (konsept)",
      privacy: "Bilgileriniz yalnızca bu sekmede tutulur ve hiçbir yere gönderilmez.",
    },

    payment: {
      title: "Burada ödeme sayfası açılırdı",
      body: "Gerçek sitede bu adımda bankanın güvenli ödeme sayfası açılır. Bu bir konsept çalışmadır: kart bilgisi istenmez, ödeme alınmaz.",
      ok: "Anladım, onaya geç",
      cancel: "Geri dön",
    },

    done: {
      title: "Masanız hazır.",
      code: "Rezervasyon kodu",
      ics: "Takvime ekle (.ics)",
      map: "Adresi haritada aç",
      change: "Değişiklik için bize yazın",
      changeSubject: (code: string) => `Rezervasyon ${code} için değişiklik`,
      reminder: "Akşamınızdan 48 saat önce bir hatırlatma göndereceğiz.",
      another: "Yeni rezervasyon",
      lost: "Rezervasyon özetiniz bu oturumda kaldı. Kişisel bilgiler güvenlik için sayfa yenilenince silinir.",
      icsTitle: "Kalemkâr akşam yemeği",
      notSent: "Konsept: hiçbir bilgi gönderilmedi.",
    },

    waitlist: {
      title: "Bekleme listesi",
      sub: "En fazla üç akşam seçin. Bir masa boşalırsa sizi önce ararız.",
      prefs: "Tercih ettiğiniz akşamlar",
      add: "Akşam ekle",
      remove: "Kaldır",
      range: "Saat aralığı",
      ranges: { erken: "Erken (18.30–19.30)", gec: "Geç (21.00–21.30)", fark: "Fark etmez" },
      freeHint: (d: string, t: string) => `${d} ${t} boş, hemen ayırın`,
      take: "Bu oturumu seç",
      submit: "Listeye yazıl",
      success: "Listeye eklendiniz. Bir masa boşalırsa sizi önce ararız.",
      successNote: "Konsept: hiçbir bilgi gönderilmedi. İsterseniz aynı bilgileri e-postayla iletebilirsiniz.",
      mail: "E-postayla gönder",
      mailSubject: "Bekleme listesi talebi",
      max: "En fazla üç akşam ekleyebilirsiniz.",
      cancel: "Rezervasyona dön",
    },
  },

  invite: {
    title: "Özel davet",
    sub: "Özel oda 8 ile 14, evin tamamı 34 kişiye kadar. Menüyü şefle birlikte yazıyoruz; bu bir teklif hesaplayıcı değil, bir talep formu.",
    occasion: "Vesile",
    occasions: ["İş yemeği", "Kutlama", "Nişan sofrası", "Lansman", "Diğer"],
    people: "Kişi sayısı",
    roomHint: "8–14 kişi: özel oda (kubbeli eski kiler).",
    houseHint: "15–34 kişi: evin tamamı, avlu dahil.",
    dates: "Tercih ettiğiniz tarihler",
    datesPh: "Örn. kasımın ikinci haftası, hafta içi",
    flexible: "Tarihte esneğiz",
    menu: "Menü isteği",
    menus: ["Şefle birlikte menü yazmak", "Güz sofrası", "Alkolsüz eşleşme"],
    budget: "Kişi başı bütçe aralığı",
    budgets: ["6.000–8.000 TL", "8.000–11.000 TL", "11.000 TL üstü", "Henüz bilmiyorum"],
    note: "Eklemek istedikleriniz",
    name: "Ad soyad",
    phone: "Cep telefonu",
    email: "E-posta",
    submit: "Talebi hazırla",
    success: "Talebinizi aldık. Etkinlik ekibimiz bir iş günü içinde size döner.",
    successNote: "Konsept: hiçbir bilgi gönderilmedi. Aşağıdaki düğme aynı bilgilerle bir e-posta taslağı açar.",
    mail: "E-posta taslağını aç",
    mailSubject: "Özel davet talebi",
    errPeople: "Özel davet 8 ile 34 kişi arası için.",
    capRoom: "Özel oda: kubbeli eski kiler",
    capServe: "Sofra, şefin elinden",
    carried: "Rezervasyondaki seçimleriniz forma taşındı.",
  },

  notFound: {
    title: "Bu tabak menüde yok.",
    body: "Aradığınız sayfa mevsimle birlikte kalkmış olabilir. Sini boş, ama mutfak açık.",
    home: "Ana sayfaya dön",
    menu: "Güz sofrasına bak",
  },
};

export type Tr = typeof tr;
