// Pazı Robotik: every Turkish string on the site. Structure is language-neutral
// so an `en.ts` with the same shape can follow (not written yet; TR first).
// Status: draft copy from the plan (docs/plans/robotik.md, section 7), adapted
// to the brand name Pazı. Awaiting Raşit's approval.

import type { Config, GripperId, GripperSpec, ModelId, PatternId, ProductKind, Warning } from "@/lib/pazi/plan";

export const tr = {
  meta: {
    title: "Pazı Robotik | Hat sonu paletleme hücreleri",
    description:
      "Gebze'de hat sonu otomasyonu: çitsiz çalışan robotlu paletleme hücresi. Kolinizin ölçüsünü girin; model, kat sayısı, hız ve tahmini geri ödeme beş dakikada çıksın. Konsept çalışma.",
    ogAlt: "Pazı Robotik paletleme hücresi: robot kol iki palet arasında koli diziyor.",
  },
  brand: {
    name: "Pazı Robotik",
    short: "Pazı",
    city: "Gebze, Kocaeli",
    email: "muhendislik@pazirobotik.com.tr",
    trialEmail: "deneme@pazirobotik.com.tr",
    meaning: "Pazı: kolun yükü kaldıran kası.",
  },
  skip: "İçeriğe geç",
  concept: {
    text: "Konsept çalışma. Pazı Robotik hayali bir markadır; ürünler, değerler ve senaryolar örnektir.",
    by: "Tasarım:",
    author: "Raşit Burucu",
    href: "https://rasitburucu.com/tr",
  },
  nav: {
    label: "Ana menü",
    home: "Pazı Robotik ana sayfa",
    items: [
      { label: "Modeller", href: "/pazi/#modeller" },
      { label: "Nasıl kurulur", href: "/pazi/#kurulum" },
      { label: "Güvenlik", href: "/pazi/#guvenlik" },
      { label: "Deneme hücresi", href: "/pazi/#deneme" },
      { label: "Biz kimiz", href: "/pazi/biz-kimiz/" },
    ],
    cta: "Ön fizibilite",
    menu: "Menü",
    close: "Menüyü kapat",
  },

  hero: {
    title: ["Hat sonunda", "kimse 25 kilo", "kaldırmasın."],
    sub: "Pazı Robotik, gıda, içecek ve kimya fabrikalarına çitsiz çalışan robotlu paletleme hücresi kurar. Ürününüzün ölçüsünü girin; hangi model, palet kaç kat, hattınıza yetişiyor mu, beş dakikada görün.",
    plateTitle: "Ürününüz",
    plateNote: "Değeri değiştirin; robot yeni deseni dizmeye başlar.",
    cta: "Bu ölçüyle devam et",
    secondary: "Önce kolinizi ölçeriz, robotu sonra seçeriz.",
    live: "Canlı hücre özeti",
  },

  fields: {
    kind: "Ürün tipi",
    kinds: { koli: "Koli", torba: "Torba", shrink: "Shrink paket" } satisfies Record<ProductKind, string>,
    size: "Ölçü (U × G × Y)",
    u: "Uzunluk",
    g: "Genişlik",
    y: "Yükseklik",
    kg: "Ağırlık",
    rate: "Dakikada ürün",
    lines: "Beslenen hat",
    shifts: "Vardiya",
    pallet: "Palet",
    pallets: { eur: "EUR 800 × 1.200", end: "Endüstriyel 1.000 × 1.200", ozel: "Özel ölçü" },
    pl: "Palet uzunluğu",
    pw: "Palet genişliği",
    maxH: "En yüksek yük",
    maxHHint: "Paletin üstünden ölçülür; palet tahtası (144 mm) hariç.",
    sheet: "Katlar arasına ara karton",
    pattern: "Desen",
    patterns: { oto: "Otomatik", sutun: "Sütun", orgu: "Örgü", firildak: "Fırıldak" } satisfies Record<"oto" | PatternId, string>,
    patternHint: {
      sutun: "Bütün ürünler aynı yönde. Çoğu zaman en çok ürün sığar ama katlar birbirine bağlanmaz.",
      orgu: "Bir blok düz, bir şerit dönük; katlar sırayla aynalanır, ek yerleri üst üste gelmez.",
      firildak: "Dört blok merkezin etrafında döner; kare palet ve uygun oranlı kolide en sağlam dizilim.",
    } satisfies Record<PatternId, string>,
    patternOff: "Bu ölçüye sığmıyor",
    step: "Değeri değiştir",
    minus: "Azalt",
    plus: "Artır",
    example: "örnek",
  },
  units: { mm: "mm", kg: "kg", perMin: "/dk", tl: "TL", month: "ay", m2: "m²", pct: "%" },

  hmi: {
    label: "Hücre durumu",
    layer: "Kat",
    perLayer: "Koli/kat",
    required: "Gerekli",
    capacity: "Kapasite",
    model: "Model",
    status: "Durum",
    ok: "Uygun",
    custom: "Özel proje",
    slow: "Yetişmiyor",
    summary: (o: { model: string; layer: number; layers: number; perLayer: number; required: number; capacity: string; status: string }) =>
      `Model ${o.model}. Kat ${o.layer} / ${o.layers}, katta ${o.perLayer} ürün. Gerekli hız dakikada ${o.required}, kapasite dakikada yaklaşık ${o.capacity}. Durum: ${o.status}.`,
  },

  view: {
    label: "Hücre görünümü",
    iso: "İzometrik",
    top: "Üstten",
    op: "Operatör gözü",
    time: "Zaman",
    speed1: "Gerçek hız",
    speed4: "4× hızlı",
    pause: "Durdur",
    play: "Sürdür",
    dragHint: "Zemindeki operatör işaretini sürükleyin.",
    still: "Bu cihaz 3B hücreyi çalıştırmıyor; aynı hesapla çizilmiş durağan görünüm gösteriliyor.",
  },

  steps: {
    id: "kurulum",
    title: "Kat kat kurulum",
    lead: "Bir hücre beş adımda kurulur. Her adım bir kat; süreler tipiktir, fabrikaya göre değişir.",
    items: [
      { name: "Keşif ziyareti", time: "tipik 1 gün", text: "Hattınızı, kolinizi ve paletinizi yerinde ölçeriz. Hücrenin oturacağı alanı, forklift yolunu ve elektrik/hava bağlantısını işaretleriz." },
      { name: "Numune testi", time: "tipik 1 hafta", text: "Gebze'deki deneme hücremizde kendi ürününüzle deneriz. Tutucu ve desen burada kesinleşir; videosunu size göndeririz." },
      { name: "Hücre kurulumu", time: "tipik 2–3 gün", text: "Hücre hazır modüller hâlinde gelir; zemine sabitlenir, alan tarayıcı bölgeleri ölçülerek ayarlanır, hattınıza bağlanır." },
      { name: "Operatör eğitimi", time: "tipik 2 gün", text: "Yeni deseni operatörünüz öğretir: ürün değişince mühendis çağırmazsınız, desen tabletten seçilir." },
      { name: "Servis", time: "sürekli", text: "Uzaktan bağlantı, yedek parça ve yeni vardiya eğitimi. Robot durursa kime ulaşacağınız bellidir." },
    ],
  },

  models: {
    id: "modeller",
    title: "Üç model, tek hücre",
    lead: "Model kataloğa bakılarak değil, kolinizin ağırlığına ve paletinizin yüksekliğine bakılarak seçilir.",
    note: "Konsept ürünler. Tablodaki bütün değerler örnektir; aynı sınıftaki iş birlikçi robotların aralığında seçilmiştir.",
    caption: "Pazı modelleri teknik föy karşılaştırması (örnek değerler)",
    fit: {
      p12: "Hafif koli ve paketler, hızlı hat",
      p20: "Orta ağırlıkta koli, uzun erişim, endüstriyel palet",
      p30: "25 kg torba ve ağır koli",
    } satisfies Record<ModelId, string>,
    rows: {
      payload: "Taşıma kapasitesi (tutucu dahil)",
      reach: "Erişim",
      repeat: "Tekrarlanabilirlik",
      axes: "Eksen",
      stackFixed: "Palet yüksekliği, sabit ayak",
      stackLift: "Palet yüksekliği, asansörlü",
      cycles: "Hafif yükte çevrim",
      mass: "Robot ağırlığı",
      ip: "Koruma sınıfı",
    },
    open: "Föyü aç",
    elevation: "Yan görünüş, ölçüler mm",
    sameScale: "Üç çizim aynı ölçekte; boyları ve erişimleri doğrudan kıyaslanabilir.",
    legend: { axis: "Eksen çizgisi", reach: "Erişim zarfı (ön yarı taralı)", load: "Örnek ürün ve palet" },
    drawing: {
      view: "Yan görünüş",
      unit: "ölçüler mm",
      sample: "örnek değer",
      label: (o: { name: string; d1: string; a2: string; a3: string; wrist: string; reach: string; gripper: string; load: string; gap: string }) =>
        `Pazı ${o.name} yan görünüş. Omuz ekseni yerden ${o.d1} mm, üst kol ${o.a2} mm, ön kol ${o.a3} mm, bilek ${o.wrist} mm; erişim yarıçapı ${o.reach} mm. Kol, ${o.gripper} ile örnek bir ${o.load} taşıyor; palet istasyonu robot ekseninden ${o.gap} mm ileride başlıyor.`,
    },
  },

  safety: {
    id: "guvenlik",
    title: "Çit yok, sınır var.",
    lead: "Alan tarayıcı insanı görür: yaklaşınca robot yavaşlar, iç bölgeye girince durur. Deneyin.",
    howto: "Operatör işaretini plan üzerinde sürükleyin ya da aşağıdaki düğmeleri kullanın. Klavyede işarete gelip ok tuşlarıyla da taşıyabilirsiniz.",
    marker: "Operatör işareti",
    places: { out: "Hücrenin dışında", slow: "Uyarı bölgesinde", stop: "Koruma bölgesinde" },
    status: { out: "Tam hız", slow: "Yavaşladı", stop: "Durdu" },
    statusLong: {
      out: "Operatör hücrenin dışında. Robot tam hızda çalışıyor.",
      slow: "Operatör uyarı bölgesinde. Robot hızını düşürdü (örnek ayar: %30).",
      stop: "Operatör koruma bölgesinde. Robot güvenli biçimde durdu; operatör çıkınca kendiliğinden devam eder.",
    },
    legend: { slow: "Uyarı bölgesi", stop: "Koruma bölgesi", reach: "Robot erişimi" },
    planTitle: "Hücre üst görünüşü",
    lines: [
      { title: "Alan tarayıcı", text: "Zemin hizasında iki bölge tarar. Uyarı bölgesinde hız düşer, koruma bölgesinde robot durur. Sınırlar kurulumda ölçülerek ayarlanır." },
      { title: "Hız ve kuvvet sınırlama", text: "İş birlikçi robotun eklemleri temas kuvvetini izler. Beklenmeyen bir temasta kol durur ve geri çekilir." },
      { title: "Risk değerlendirmesi", text: "Her hücre için kurulumdan önce risk değerlendirmesi yapılır; teknik dosya ve kullanım talimatı CE dosyasıyla teslim edilir." },
    ],
  },

  scenarios: {
    id: "senaryolar",
    title: "Üç örnek iş",
    lead: "Hat sonunda en sık gördüğümüz üç ürün. Değerler örnektir; açtığınızda hepsini değiştirebilirsiniz.",
    tag: "Örnek senaryo",
    open: "Bu senaryoyu aç",
    items: [
      { key: "torba", name: "25 kg yapı kimyasalı torbası", where: "Dilovası, yapı kimyasalı", text: "Toz harç ve yapıştırıcı torbaları. Vakum dokuma torbada tutmaz; tutucu pençe olur." },
      { key: "shrink", name: "İçecek shrink paketi", where: "Bursa, içecek", text: "Altılı 1,5 litre şişe paketi. Hat hızlı olduğu için robot iki paketi birden alır." },
      { key: "dondurulmus", name: "Dondurulmuş gıda kolisi", where: "Konya, gıda", text: "Soğuk depo girişinde elle dizilen koliler. Ara karton palet sağlamlığını korur." },
    ],
  },

  savings: {
    id: "tasarruf",
    title: "Satın alın ya da kiralayın.",
    lead: "Önce tasarrufu görün. Robot fiyatını biz yazmıyoruz; teklif tutarınızı tam hesapta kendiniz girersiniz.",
    shifts: "Vardiya sayısı",
    people: "Vardiyada bu işi yapan kişi",
    wage: "Kişi başı aylık brüt maliyet",
    wageHint: "Örnek değerle dolu; kendi rakamınızı yazın.",
    saving: "Aylık işçilik tasarrufu",
    ceiling: "18 ayda kendini ödeyen yatırım sınırı",
    ceilingHint: "Teklif bu aralığın altındaysa hücre 18 ayda kendini öder.",
    estimate: "tahmini",
    note: "Tahmindir. Vergi, teşvik ve finansman dahil değildir; kesin hesap keşif ziyaretinden sonra.",
    cta: "Teklif tutarınızla tam hesap",
    assumptions: "Varsayım: robot işin %85'ini devralır (palet değişimi ve gözetim kalır); yıllık bakım ve enerji yatırımın %4'ü; ±%15 bant.",
  },

  trial: {
    id: "deneme",
    title: "Ürününüzü getirin, deneyelim.",
    lead: "Gebze'deki deneme hücremize bir palet kolinizi getirin. Kendi ürününüzle, kendi deseninizle robotu çalışırken görün; videosu ve ölçüm notları sizde kalsın.",
    address: ["Gebze Organize Sanayi Bölgesi", "Gebze, Kocaeli", "[örnek adres]"],
    hours: "Hafta içi 08.30–17.30, randevuyla",
    cta: "Deneme randevusu iste",
    directions: "Yol tarifi",
    mapsHref: "https://www.google.com/maps/search/?api=1&query=Gebze+Organize+Sanayi+B%C3%B6lgesi",
    drawing: "Deneme atölyesinin izometrik çizimi: yükleme kapısı, numune paleti, deneme hücresi ve toplantı odası.",
    labels: { dock: "Yükleme kapısı", sample: "Numune paleti", cell: "Deneme hücresi", room: "Video ve rapor" },
    mailSubject: "Deneme hücresi randevusu",
    mailBody: "Merhaba,\n\nGebze deneme hücrenizde ürünümüzü denemek istiyoruz.\n\nÜrün:\nYaklaşık tarih:\nFirma:\nTelefon:\n\nTeşekkürler.",
  },

  service: {
    id: "servis",
    title: "Robot durursa ne olur?",
    lead: "Hat sonunda duran robot, bütün hattı durdurur. Bunu bilerek kuruyoruz.",
    items: [
      { title: "Uzaktan bağlantı", text: "Hücre izin verdiğiniz anda uzaktan bağlanılabilir. Hata kaydını görür, çoğu sorunu yerinden kalkmadan çözeriz.", tag: "hedef: aynı iş günü" },
      { title: "Yedek parça", text: "Tutucu, vakum pedi ve tarayıcı gibi aşınan parçalar Gebze'de stokta durur.", tag: "hedef: 48 saatte sahada" },
      { title: "Eğitim", text: "Kurulum haftasında operatör ve bakım eğitimi; yeni vardiya ya da yeni ürün geldiğinde tekrar.", tag: "kurulumla birlikte" },
    ],
    teardown: "Kolu söküp gösterelim",
  },

  story: {
    title: "Neden Pazı",
    text: [
      "Pazı Robotik'i, Dilovası'nda bir boya fabrikasının hat sonunda bakım mühendisliği yapmış biriyle bir endüstriyel yazılımcı kurdu.",
      "Her vardiya yüzlerce kez elle kaldırılan 25 kiloluk torbaları izleyen ilk kurucu, büyük ve çitli robot hücrelerinin küçük fabrikaya hem pahalı hem yer kaplayan bir çözüm olduğunu gördü.",
      "İkisi, operatörün tabletten yeni desen öğretebildiği ve kiralanabilen bir hücre tasarladı; Gebze'deki atölyelerinde bugün de her müşterinin kendi ürünüyle deneme yapılıyor.",
    ],
  },

  footer: {
    title: "Hat sonunuzu birlikte ölçelim.",
    contact: "İletişim",
    pages: "Sayfalar",
    links: [
      { label: "Ön fizibilite", href: "/pazi/fizibilite/" },
      { label: "Biz kimiz", href: "/pazi/biz-kimiz/" },
      { label: "P12 föyü", href: "/pazi/modeller/p12/" },
      { label: "P20 föyü", href: "/pazi/modeller/p20/" },
      { label: "P30 föyü", href: "/pazi/modeller/p30/" },
    ],
    credits: "Kaynaklar ve lisanslar",
    privacy: "Bu demo hiçbir veri toplamaz. Formlar e-posta taslağı açar; sunucuya bir şey gönderilmez.",
    concept: "Konsept çalışma: Pazı Robotik, ürünleri, adresi ve senaryoları hayalidir. Tasarım ve kod: Raşit Burucu.",
  },

  warnings: {
    "over-cobot": "Bu yük cobot sınıfının üstünde. Çitli endüstriyel robot gerekir; bu bir özel proje.",
    overhang: "Ürün palet kenarından taşıyor. Ürünü döndürmeyi ya da palet ölçüsünü değiştirmeyi deneyin.",
    "weight-limited": "Palet yükü 1.000 kg sınırını aşıyordu; kat sayısı buna göre sınırlandı.",
    "needs-lift": "Palet yüksekliği sabit ayağın erişimini aşıyor: asansör kolonu eklendi.",
    "needs-double": "Tek ürünle hat hızına yetişmiyor: çift tutucu (iki ürün birden) eklendi.",
    "too-slow": "Bu hız tek hücreyle karşılanmıyor. Hattı bölmek ya da özel bir hat sonu çözümü gerekir.",
    "two-cells": "Tek robot yetişmez. İki hücre ya da hattın ikiye bölünmesi önerilir.",
    "no-reach": "Paletin uzak köşesi bu modelin erişimi dışında kalıyor.",
    "bag-claw": "Torba için tutucu pençedir; vakum dokuma torbada güvenli tutmaz.",
    "column-unstable": "Sütun dizilimde katlar birbirine bağlanmaz; streç sarma ya da ara karton önerilir.",
    "grip-small": "Ürün standart tutucu için küçük: vantuzlar ya da pençe parmakları ürünü güvenle kavrayamıyor. Ürüne özel tutucu gerekir.",
    "grip-large": "Ürün standart tutucu sınıfından büyük: vakum plakası ya da pençe açıklığı yetmiyor. Özel tutucu gerekir.",
    "grip-heavy": "Bu ağırlık, standart tutucunun güvenle taşıyabileceğinin üstünde: ürünün üstüne sığan vantuz ya da parmak sayısı yetmiyor. Mekanik destekli özel tutucu gerekir.",
  } satisfies Record<Warning, string>,
  overhangMm: (mm: number) => `Taşma ${mm} mm.`,

  errors: {
    range: (lo: string, hi: string) => `${lo} ile ${hi} arasında bir değer girin.`,
    pallet: "Bu ölçü palet ölçüsünden büyük.",
    empty: "Bir değer girin; boş bırakırsanız örnek değer kullanılır.",
    taller: "Ürün, en yüksek yükten uzun olamaz.",
  },

  grippers: {
    vakum: "Vakum tutucu",
    "vakum-iki": "İki bölgeli vakum tutucu",
    "vakum-uzun": "Uzun plakalı vakum tutucu",
    "cift-vakum": "Çift vakum tutucu (iki ürün)",
    pence: "Torba pençesi",
  } satisfies Record<GripperId, string>,
  /** One line under the tool name: size, pads or fingers, mass. Concept values. */
  gripSize: (g: GripperSpec) => {
    const n = (v: number) => new Intl.NumberFormat("tr-TR").format(v);
    const kg = new Intl.NumberFormat("tr-TR", { maximumFractionDigits: 1 }).format(g.mass);
    if (g.claw) return `Çatal ${n(g.plate.l)} mm boyunda, açılınca ${n(g.claw.open)} mm; her yanda ${g.claw.fingers} parmak · ~${kg} kg`;
    const pads = `${g.pads.nx}×${g.pads.nz} vantuz Ø${g.pads.d}`;
    return `Plaka ${n(g.plate.l)} × ${n(g.plate.w)} mm, ${pads}${g.zones === 2 ? ", iki bölge" : ""} · ~${kg} kg`;
  },
  gripCustom: "Özel tutucu gerekir",

  flow: {
    title: "Hat sonu ön fizibilite",
    lead: "Altı adım. Her değişiklik adres çubuğuna yazılır; bağlantıyı satın almacınıza gönderebilirsiniz. Kişisel bilgi adrese asla yazılmaz.",
    steps: ["Ürün", "Hat", "Palet", "Sonuç", "Geri ödeme", "Gönder"],
    stepOf: (i: number, n: number) => `Adım ${i} / ${n}`,
    back: "Geri",
    next: "Devam",
    skip: "Bu adımı atla",
    preview: "Canlı önizleme",
    product: { title: "Ürününüz", lead: "Hat sonunda palete inen ürün. Ölçüyü ürünün dış ölçüsünden alın." },
    line: { title: "Hattınız", lead: "Robotun yetişmesi gereken hız. İki hat seçerseniz iki konveyör aynı hücreye gelir." },
    pallet: { title: "Paletiniz", lead: "Desen otomatik önerilir; isterseniz elle seçin. Kat planı ölçülü çizilir." },
    plan: "Kat planı (üstten, ölçüler mm)",
    planOdd: "Tek katlar",
    planEven: "Çift katlar",
    numbers: { perLayer: "Kat başına ürün", layers: "Kat sayısı", total: "Palet başına ürün", fill: "Palet alanı doluluğu", height: "Toplam palet yüksekliği", load: "Palet yükü" },
    result: {
      title: "Önerilen hücre",
      lead: "Her rakam tahminidir; varsayımlar aşağıda.",
      model: "Model",
      gripper: "Tutucu",
      sample: "örnek ölçü",
      gripNearest: "Standart sınıfta en yakın",
      capacity: "Kapasite",
      required: "Gerekli",
      cycle: "Çevrim süresi",
      area: "Hücre taban alanı",
      options: "Eklenen opsiyonlar",
      none: "Opsiyon gerekmiyor",
      lift: "Asansör kolonu",
      double: "Çift tutucu",
      sheet: "Ara karton yerleştirici",
      safety: "Güvenlik: iki bölgeli alan tarayıcı, hız ve kuvvet sınırlama, kurulum öncesi risk değerlendirmesi.",
      customTitle: "Standart hücre bu işe uymuyor.",
      customText: "Bu bir eksiklik değil, özel proje demek. Ölçülerinizle bir mühendisimiz sizi arasın.",
      assumptions: "Varsayımlar",
      assumptionList: [
        "Çevrim süresi: al-kaldır-taşı-in-bırak hareketi, yüke ve palet yüksekliğine göre yavaşlatılarak hesaplandı.",
        "Hız, iş birlikçi modda (çitsiz) çalışmaya göre sınırlıdır; uyarı bölgesinde robot yavaşlar.",
        "Palet yükü 1.000 kg ile sınırlandı. Palet tahtası 144 mm sayıldı.",
        "Hücre taban alanı iki palet istasyonu, robot ve konveyör ucunu kapsar; tarayıcı bölgeleri hariç.",
      ],
      estimate: "tahmini",
      locked: (m: string) => `${m} modeline göre hesaplandı.`,
      unlock: "Modeli serbest bırak",
    },
    payback: {
      title: "Geri ödeme",
      lead: "İsteğe bağlı. Teklif tutarınızı biliyorsanız girin; bilmiyorsanız atlayın.",
      mode: "Alım şekli",
      modes: { satin: "Satın alma", kira: "Kiralama" },
      people: "Vardiyada bu işi yapan kişi",
      wage: "Kişi başı aylık brüt maliyet",
      invest: "Yatırım tutarı (teklifiniz)",
      investHint: "Robot fiyatı yazmıyoruz; aldığınız ya da beklediğiniz teklifi girin.",
      rent: "Aylık kira (teklifiniz)",
      saving: "Aylık işçilik tasarrufu",
      upkeep: "Aylık bakım ve enerji payı",
      months: "Tahmini geri ödeme",
      monthsValue: (a: number, b: number) => (a === b ? `${a} ay` : `${a}–${b} ay`),
      rentGap: "Kira sonrası aylık fark",
      rentOk: "Aylık kira, işçilik tasarrufunun altında: kiralama ilk aydan kendini öder.",
      rentNo: "Bu senaryoda kira, tasarrufun üstünde kalıyor.",
      never: "Bu senaryoda robot kendini ödemiyor. Vardiya sayısı artarsa tablo değişir.",
      empty: "Tutarı girdiğinizde aralık burada görünür.",
      note: "Tahmindir. Vergi, teşvik ve finansman dahil değildir; kesin hesap keşif ziyaretinden sonra.",
    },
    send: {
      title: "Gönderin",
      lead: "Dört yol var. Hiçbiri veri toplamaz: e-posta taslağı sizin programınızda açılır.",
      engineer: "Mühendise gönder",
      engineerLead: "Ölçüleriniz ve sonuç e-postanın gövdesine yazılır.",
      name: "Ad soyad",
      company: "Firma",
      email: "E-posta",
      phone: "Telefon (isteğe bağlı)",
      city: "Fabrika şehri",
      note: "Not (isteğe bağlı)",
      submit: "E-posta taslağını aç",
      print: "Ön föyü yazdır",
      printLead: "Bu yapılandırmaya özel A4 özet; tarayıcıdan PDF olarak kaydedebilirsiniz.",
      copy: "Bağlantıyı kopyala",
      copyLead: "Satın almacınıza ya da ekibinize; yalnızca ürün ve palet verisi taşır.",
      copied: "Bağlantı kopyalandı.",
      copyFail: "Kopyalanamadı; adres çubuğundaki bağlantıyı kullanın.",
      trial: "Deneme hücresi randevusu iste",
      required: "Bu alan gerekli.",
      emailBad: "E-posta biçimini kontrol edin; örneğin ad@firma.com.tr",
      done: "Taslak e-postanız açıldı. Gönder'e bastığınızda mühendisimize ulaşır.",
      doneNote: "Bu demo hiçbir veri toplamaz.",
      fallback: "E-posta programınız açılmadıysa özeti kopyalayıp kendiniz gönderin:",
      copySummary: "Özeti kopyala",
      subject: "Hat sonu ön fizibilite",
    },
    noscript: "Ön fizibilite aracı JavaScript ile çalışır. Ölçülerinizi doğrudan e-postayla gönderebilirsiniz:",
  },

  sheet: {
    title: "Teknik föy",
    configTitle: "Ön fizibilite föyü",
    print: "Yazdır / PDF olarak kaydet",
    back: "Geri dön",
    concept: "Konsept ürün. Bütün değerler örnektir; teklif ve sözleşme yerine geçmez.",
    date: "Tarih",
    ref: "Yapılandırma bağlantısı",
    product: "Ürün",
    line: "Hat",
    pallet: "Palet",
    result: "Sonuç",
    payback: "Geri ödeme",
    who: "Kime uygun",
    forThis: "Bu model sizin için mi?",
    forThisCta: "Kendi ölçünüzle deneyin",
    sheetCta: "Teknik föyü yazdır",
    cycleLabel: "Bu model, kendi sınıfına uygun örnek ürünle çalışıyor.",
    safety: "Güvenlik",
    safetyText: "İki bölgeli alan tarayıcı (uyarı bölgesinde yavaşlar, koruma bölgesinde durur), hız ve kuvvet sınırlama, kurulum öncesi risk değerlendirmesi ve CE teknik dosyası.",
    cellTitle: "Örnek hücre, izometrik",
    cellNote: "Kendi sınıfına uygun örnek ürünle; iki palet istasyonu, konveyör ucu ve tarayıcı bölgeleri.",
  },

  // "Biz kimiz": the teardown page. Draft copy, awaiting Raşit's approval.
  about: {
    meta: {
      title: "Biz kimiz",
      description:
        "Pazı Robotik'i bir bakım mühendisi ile bir endüstriyel yazılımcı kurdu. Kurduğumuz kolu vidasına kadar biliriz: kaydırın, P30'u sahada söküldüğü sırayla açalım. Konsept çalışma.",
      ogAlt: "Pazı P30 robot kolun patlatılmış görünüşü: on beş parça, eklem eksenleri boyunca ayrılmış.",
    },
    intro: {
      title: "Kurduğumuz kolu vidasına kadar biliriz.",
      story: [
        "Pazı'yı, Dilovası'nda bir boya fabrikasının hat sonunda bakım mühendisliği yapmış biriyle bir endüstriyel yazılımcı kurdu.",
        "Biri duran bir robotun başında yedek parça beklemenin ne demek olduğunu bilir; öteki o robotun yazılımını yazar.",
        "Bu yüzden sattığımız kolu parça parça tanırız. Sahada bir eklem arıza verirse hangi parçanın değişeceğini de biliriz.",
      ],
      hint: "Kaydırın: kolu sahada söküldüğü sırayla açalım.",
    },
    teardown: {
      id: "pazinin-ici",
      title: "Pazının içi",
      lead: "P30, sahada söküldüğü sırayla: önce kablo ve tutucu, en son taban.",
      hold: "Her eklem ayrı bir modül. Arıza veren modül değişir, kolun geri kalanı yerinde kalır.",
      done: "Yerine oturdu. Kol hücrede, torbayı palete koyuyor.",
      listTitle: "Parça listesi, söküm sırasıyla",
      part: "Parça",
      module: "Modül",
      status: "Durum",
      none: "Kol monte",
      phases: { ready: "Hazır", apart: "Sökülüyor", open: "Açık", together: "Montaj", work: "Çalışıyor" },
      drawing:
        "Pazı P30 robot kolun yan görünüşü, patlatılmış: kablo hattı, torba pençesi, alet flanşı, bilek modülleri, ön kol, dirsek, üst kol, omuz kapağı, fren, servo motor, redüktör, taban eklemi ve taban flanşı eklem eksenleri boyunca ayrılmış; yanda kontrol kutusu ve alan tarayıcı.",
      scene: "Üç boyutlu söküm sahnesi. Aynı bilgi aşağıdaki parça listesinde sıralı olarak var.",
    },
    // order = the order a technician takes the arm apart (see components/pazi/about/model.ts)
    parts: {
      hose: { name: "Kablo hattı", code: "", text: "Güç, sinyal ve hava tek kılıfta. Klipslerden çıkar, tek parça değişir." },
      gripper: { name: "Torba pençesi", code: "", text: "25 kg dokuma torbayı iki yandan kavrar. Hızlı değiştiriciden tek kilitle ayrılır." },
      toolFlange: { name: "Alet flanşı", code: "ISO 9409", text: "Standart bağlantı: tutucu değişse de vida düzeni aynı kalır." },
      wrist: { name: "Bilek modülleri", code: "J4–J6", text: "Üç eksen, aynı yapıda üç modül. Biri arızalanırsa yalnız o değişir." },
      forearm: { name: "Ön kol", code: "", text: "Dirsek ile bilek arasındaki taşıyıcı tüp." },
      elbow: { name: "Dirsek", code: "J3", text: "Ön kolu kaldıran eklem; içinde omuzdakinin küçüğü bir motor ve redüktör var." },
      upperArm: { name: "Üst kol", code: "", text: "Omuz ile dirsek arasındaki ana tüp. Model etiketi bunun üstünde." },
      shoulderCover: { name: "Omuz kapağı", code: "J2", text: "Kapak açılınca eklemin iç parçalarına önden ulaşılır." },
      brake: { name: "Fren", code: "", text: "Elektrik kesilince kolu olduğu yerde tutar." },
      motor: { name: "Servo motor", code: "", text: "Eklemi döndürür; arkasındaki enkoder konumu her an okur." },
      gearbox: { name: "Redüktör", code: "", text: "Dalga dişli: motorun hızını düşürür, torku artırır, boşluksuz çalışır." },
      base: { name: "Taban eklemi", code: "J1", text: "Kolu dikey eksen etrafında çevirir." },
      mount: { name: "Taban flanşı", code: "", text: "Sekiz cıvatayla zemine ya da asansör kolonuna bağlanır." },
      controller: { name: "Kontrol kutusu", code: "", text: "Eksen sürücüleri, güvenlik rölesi ve hat bağlantısı. Kapağı önden açılır." },
      scanner: { name: "Alan tarayıcı", code: "", text: "İnsanı görür: uyarı bölgesinde yavaşlatır, koruma bölgesinde durdurur." },
    },
    principles: {
      id: "nasil-calisiyoruz",
      title: "Nasıl çalışıyoruz",
      lead: "Kolu tanımak işin yarısı. Öteki yarısı, kol sizin hattınızdayken ne yaptığımız.",
      head: { what: "İlke", how: "Ne demek", when: "Ne zaman" },
      items: [
        {
          title: "Kendi atölyemizde deneriz",
          text: "Robotu sahaya getirmeden önce sizin ürününüzle Gebze'deki deneme hücresinde çalıştırırız. Tutucu ve desen orada kesinleşir.",
          when: "her projede",
        },
        {
          title: "Operatöre öğretiriz",
          text: "Yeni ürün geldiğinde deseni operatörünüz tabletten seçer. Kurulum haftasında öğretir, yeni vardiyada tekrarlarız.",
          when: "kurulum haftası",
        },
        {
          title: "Yedek parçayı stokta tutarız",
          text: "Yukarıda söktüğümüz modüllerin aşınanları Gebze'deki rafta durur: tutucu, bilek modülü, kablo hattı, tarayıcı.",
          when: "hedef: 48 saatte sahada",
        },
        {
          title: "Uzaktan bağlanırız",
          text: "İzin verdiğiniz anda hücrenin hata kaydını görürüz; çoğu arızayı kimse yola çıkmadan çözeriz.",
          when: "hedef: aynı iş günü",
        },
      ],
    },
    workshop: {
      id: "atolye",
      title: "Atölye Gebze'de.",
      text: "Deneme hücresi, yedek parça rafı ve eğitim masası aynı çatı altında. Bir palet ürününüzü getirin; kolu çalışırken de, sökülürken de görün.",
      cta: "Ürününüzü getirin",
      flow: "Ön fizibilite",
      flowLead: "Ölçünüz hazırsa önce beş dakikalık ön fizibiliteyle başlayın.",
    },
  },

  notFound: {
    title: "Bu koli palete sığmadı.",
    text: "Aradığınız sayfa yok ya da taşındı.",
    home: "Ana sayfaya dön",
    flow: "Ön fizibiliteye git",
  },

  credits: {
    title: "Kaynaklar ve lisanslar",
    lead: "Bu konsept sitede kullanılan dış varlıklar. Robot, hücre ve bütün çizimler kodla üretildi; fotoğraf ya da hazır 3B model yok.",
  },
};

export type Tr = typeof tr;

/** Example configurations behind the three scenarios (values are examples). */
/** The home page opens on the headline's own case: a 25 kg bag. */
export const heroConfig: Partial<Config> = { kind: "torba", u: 600, g: 400, y: 120, kg: 25, rate: 5, lines: 1, shifts: 3, pallet: "eur", maxH: 1300, sheet: false, pattern: "oto" };

export const scenarioConfigs: Record<string, Partial<Config>> = {
  torba: { kind: "torba", u: 600, g: 400, y: 120, kg: 25, rate: 5, lines: 1, shifts: 3, pallet: "eur", maxH: 1300, sheet: false, pattern: "oto" },
  shrink: { kind: "shrink", u: 270, g: 180, y: 330, kg: 9.6, rate: 14, lines: 1, shifts: 2, pallet: "eur", maxH: 1350, sheet: false, pattern: "oto" },
  dondurulmus: { kind: "koli", u: 380, g: 290, y: 200, kg: 8, rate: 9, lines: 1, shifts: 2, pallet: "eur", maxH: 1400, sheet: true, pattern: "oto" },
};
